# Generated by Django 4.0 on 2022-01-11 13:46

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import api.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algo",
            fields=[
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.IntegerField(
                        choices=[(0, "ALGO_UNKNOWN"), (1, "ALGO_SIMPLE"), (2, "ALGO_AGGREGATE"), (3, "ALGO_COMPOSITE")]
                    ),
                ),
                (
                    "description_address",
                    models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()]),
                ),
                ("description_checksum", models.CharField(max_length=64)),
                (
                    "algorithm_address",
                    models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()]),
                ),
                ("algorithm_checksum", models.CharField(max_length=64)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("owner", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("channel", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["creation_date", "key"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "description_address",
                    models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()]),
                ),
                ("description_checksum", models.CharField(max_length=64)),
                ("metric_address", models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()])),
                ("metric_checksum", models.CharField(max_length=64)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("owner", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("channel", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["creation_date", "key"],
            },
        ),
    ]
