# Generated by Django 4.0.2 on 2022-02-22 07:52

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_computeplan_computetask"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.FloatField()),
                ("creation_date", models.DateTimeField()),
                ("channel", models.CharField(max_length=100)),
                (
                    "compute_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="performances",
                        to="api.computetask",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="performances",
                        to="api.metric",
                    ),
                ),
            ],
            options={
                "unique_together": {("compute_task", "metric")},
            },
        ),
    ]
