# Generated by Django 4.0.2 on 2022-02-23 10:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models

import api.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_performance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.IntegerField(choices=[(0, "MODEL_UNKNOWN"), (1, "MODEL_SIMPLE"), (2, "MODEL_HEAD")]),
                ),
                (
                    "model_address",
                    models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()], null=True),
                ),
                ("model_checksum", models.CharField(max_length=64)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("owner", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField()),
                ("channel", models.CharField(max_length=100)),
                (
                    "compute_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="models", to="api.computetask"
                    ),
                ),
            ],
            options={
                "ordering": ["creation_date", "key"],
            },
        ),
    ]
