# Generated by Django 4.0.2 on 2022-03-01 09:00

from django.db import migrations
from django.db import models

import api.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="computetask",
            name="logs_address",
            field=models.URLField(null=True, validators=[api.models.utils.URLValidatorWithOptionalTLD()]),
        ),
        migrations.AddField(
            model_name="computetask",
            name="logs_checksum",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="computetask",
            name="logs_owner",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
