# Generated by Django 4.0.3 on 2022-04-08 20:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_computetask_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algo",
            name="category",
            field=models.IntegerField(
                choices=[
                    (0, "ALGO_UNKNOWN"),
                    (1, "ALGO_SIMPLE"),
                    (2, "ALGO_AGGREGATE"),
                    (3, "ALGO_COMPOSITE"),
                    (4, "ALGO_METRIC"),
                ]
            ),
        ),
    ]
