# Generated by Django 4.0.4 on 2022-05-10 08:13

from django.db import migrations
from django.db import models


def migrate_data(apps, schema_editor):
    category_mapping = {
        1: "ALGO_SIMPLE",
        2: "ALGO_AGGREGATE",
        3: "ALGO_COMPOSITE",
        4: "ALGO_METRIC",
    }
    algo_model = apps.get_model("api", "algo")
    for algo_instance in algo_model.objects.all():
        algo_instance.category = category_mapping[algo_instance.category_int]
        algo_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_computetask_metrics_alter_performance_metric_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="algo",
            old_name="category",
            new_name="category_int",
        ),
        migrations.AddField(
            model_name="algo",
            name="category",
            field=models.CharField(
                choices=[
                    ("ALGO_SIMPLE", "Algo Simple"),
                    ("ALGO_AGGREGATE", "Algo Aggregate"),
                    ("ALGO_COMPOSITE", "Algo Composite"),
                    ("ALGO_METRIC", "Algo Metric"),
                ],
                max_length=64,
                default="TEMPORARY_MIGRATION_VALUE",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name="algo",
            name="category_int",
        ),
    ]
