# Generated by Django 4.0.4 on 2022-05-06 09:42

from django.db import migrations
from django.db import models


def populate_default_cp_names(apps, schema_editor):
    computeplan_model = apps.get_model("api", "computeplan")
    computeplan_model.objects.update(name=models.F("key"))


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_algo_category"),
    ]

    operations = [
        migrations.AddField(model_name="computeplan", name="name", field=models.CharField(null=True, max_length=100)),
        migrations.RunPython(populate_default_cp_names),
        migrations.AlterField(model_name="computeplan", name="name", field=models.CharField(max_length=100)),
    ]
