# Generated by Django 4.0.4 on 2022-05-19 12:35

from django.db import migrations
from django.db import models


def convert_unknown_to_empty(apps, schema_editor):
    """Iterate over existing CPs with unknown status, assume they are empty and write the new status"""
    computeplan_model = apps.get_model("api", "computeplan")
    # Hardcoding values on purpose since they shouldn't change with future evolutions of the code
    computeplan_model.objects.filter(status="PLAN_STATUS_UNKNOWN").update(status="PLAN_STATUS_EMPTY")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_algooutput_algoinput"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computeplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLAN_STATUS_UNKNOWN", "Plan Status Unknown"),
                    ("PLAN_STATUS_WAITING", "Plan Status Waiting"),
                    ("PLAN_STATUS_TODO", "Plan Status Todo"),
                    ("PLAN_STATUS_DOING", "Plan Status Doing"),
                    ("PLAN_STATUS_DONE", "Plan Status Done"),
                    ("PLAN_STATUS_CANCELED", "Plan Status Canceled"),
                    ("PLAN_STATUS_FAILED", "Plan Status Failed"),
                    ("PLAN_STATUS_EMPTY", "Plan Status Empty"),
                ],
                max_length=64,
            ),
        ),
        migrations.RunPython(convert_unknown_to_empty),
        migrations.AlterField(
            model_name="computeplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLAN_STATUS_WAITING", "Plan Status Waiting"),
                    ("PLAN_STATUS_TODO", "Plan Status Todo"),
                    ("PLAN_STATUS_DOING", "Plan Status Doing"),
                    ("PLAN_STATUS_DONE", "Plan Status Done"),
                    ("PLAN_STATUS_CANCELED", "Plan Status Canceled"),
                    ("PLAN_STATUS_FAILED", "Plan Status Failed"),
                    ("PLAN_STATUS_EMPTY", "Plan Status Empty"),
                ],
                max_length=64,
            ),
        ),
    ]
