# Generated by Django 4.0.3 on 2022-07-05 09:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_rename_channelnode_channelorganization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelorganization",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
    ]
