# Generated by Django 4.0.4 on 2022-07-13 23:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_remove_computetask_metrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeTaskOutput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=100)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outputs", to="api.computetask"
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "identifier")},
            },
        ),
    ]
