# Generated by Django 4.0.4 on 2022-07-19 14:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_computetaskoutput"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeTaskInput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=100)),
                ("position", models.IntegerField()),
                ("asset_key", models.UUIDField(blank=True, null=True)),
                ("parent_task_output_identifier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "parent_task_key",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.computetask"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inputs", to="api.computetask"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("task", "identifier", "position")},
            },
        ),
    ]
