# Generated by Django 4.0.6 on 2022-07-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_data_migration_compute_plan_cancelation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computetask",
            name="head_permissions_download_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="head_permissions_download_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="head_permissions_process_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="head_permissions_process_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="model_permissions_download_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="model_permissions_download_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="model_permissions_process_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="model_permissions_process_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="prediction_permissions_download_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="prediction_permissions_download_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="prediction_permissions_process_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="prediction_permissions_process_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="trunk_permissions_download_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="trunk_permissions_download_public",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="trunk_permissions_process_authorized_ids",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="trunk_permissions_process_public",
        ),
    ]
