# Generated by Django 4.0.4 on 2022-08-01 09:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_data_migration_compute_task_output"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastEvent",
            fields=[
                ("channel", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("event_id", models.CharField(blank=True, default="", max_length=250, null=True)),
            ],
        ),
    ]
