# Generated by Django 4.0.7 on 2022-09-07 13:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_computeplan_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeTaskOutputAsset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "asset_kind",
                    models.CharField(
                        choices=[("ASSET_MODEL", "Asset Model"), ("ASSET_PERFORMANCE", "Asset Performance")],
                        max_length=64,
                    ),
                ),
                ("asset_key", models.CharField(max_length=73)),
                (
                    "task_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="api.computetaskoutput",
                    ),
                ),
            ],
        ),
    ]
