# Generated by Django 4.0.7 on 2022-09-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_algo_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computeplan",
            name="delete_intermediary_models",
        ),
    ]
