# Generated by Django 4.0.7 on 2022-09-16 14:34

import uuid

from django.db import migrations
from django.db import models

# generate a random uniq value as temporary value for channel
DEFAULT_CHANNEL = str(uuid.uuid4())


def populate_channel(apps, schema_editor):
    algo = apps.get_model("api", "algo").objects.filter(key=models.OuterRef("algo_id"))
    apps.get_model("api", "algoinput").objects.update(channel=models.Subquery(algo.values("channel")[:1]))
    apps.get_model("api", "algooutput").objects.update(channel=models.Subquery(algo.values("channel")[:1]))

    task = apps.get_model("api", "computetask").objects.filter(key=models.OuterRef("task_id"))
    apps.get_model("api", "computetaskinput").objects.update(channel=models.Subquery(task.values("channel")[:1]))
    apps.get_model("api", "computetaskoutput").objects.update(channel=models.Subquery(task.values("channel")[:1]))

    output = apps.get_model("api", "computetaskoutput").objects.filter(id=models.OuterRef("task_output_id"))
    apps.get_model("api", "computetaskoutputasset").objects.update(
        channel=models.Subquery(output.values("channel")[:1])
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_remove_computeplan_delete_intermediary_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="algoinput",
            name="channel",
            field=models.CharField(default=DEFAULT_CHANNEL, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="algooutput",
            name="channel",
            field=models.CharField(default=DEFAULT_CHANNEL, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="computetaskinput",
            name="channel",
            field=models.CharField(default=DEFAULT_CHANNEL, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="computetaskoutput",
            name="channel",
            field=models.CharField(default=DEFAULT_CHANNEL, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="computetaskoutputasset",
            name="channel",
            field=models.CharField(default=DEFAULT_CHANNEL, max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(populate_channel),
    ]
