# Generated by Django 4.0.7 on 2022-09-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_algoinput_channel_algooutput_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="category",
        ),
    ]
