# Generated by Django 4.0.7 on 2022-09-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_setup_role_userchannel'),
        ('api', '0037_remove_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeplan',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='users.userchannel'),
        ),
    ]
