# Generated by Django 4.0.7 on 2022-09-21 10:10

from django.db import migrations


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_computetaskinputasset"),
    ]

    operations = [
        migrations.RunPython(dummy),
    ]
