# Generated by Django 4.0.7 on 2022-10-04 14:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_computetaskinputasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computeplan",
            name="failed_task_category",
            field=models.CharField(
                choices=[
                    ("TASK_UNKNOWN", "Task Unknown"),
                    ("TASK_TRAIN", "Task Train"),
                    ("TASK_AGGREGATE", "Task Aggregate"),
                    ("TASK_COMPOSITE", "Task Composite"),
                    ("TASK_PREDICT", "Task Predict"),
                    ("TASK_TEST", "Task Test"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="computetask",
            name="category",
            field=models.CharField(
                choices=[
                    ("TASK_UNKNOWN", "Task Unknown"),
                    ("TASK_TRAIN", "Task Train"),
                    ("TASK_AGGREGATE", "Task Aggregate"),
                    ("TASK_COMPOSITE", "Task Composite"),
                    ("TASK_PREDICT", "Task Predict"),
                    ("TASK_TEST", "Task Test"),
                ],
                default="TASK_UNKNOWN",
                max_length=64,
            ),
        ),
    ]
