# Generated by Django 4.0.7 on 2022-10-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0040_alter_computeplan_failed_task_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computeplan",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compute_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
