# Generated by Django 4.0.7 on 2022-10-10 07:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_computeplan_failed_task_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computetask",
            name="category",
        ),
        migrations.AlterField(
            model_name="computeplan",
            name="failed_task_category",
            field=models.CharField(default="TASK_UNKNOWN", max_length=64, null=True),
        ),
    ]
