# Generated by Django 4.0.7 on 2022-12-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_computeplan_failed_task_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computetask",
            name="parent_tasks",
        ),
    ]
