# Generated by Django 4.0.7 on 2022-12-14 14:53

from django.conf import settings
from django.db import migrations
from django.db import models

import api.models.computeplan


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0041_remove_computetask_parent_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="computeplan",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(api.models.computeplan._get_or_create_deleted_user),
                related_name="compute_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
