# Generated by Django 4.0.7 on 2023-01-17 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_alter_computeplan_failed_task_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasample",
            name="test_only",
        ),
    ]
