# Generated by Django 4.0.7 on 2023-01-18 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_remove_datasample_test_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computeplan",
            name="failed_task_category",
        ),
    ]
