# Generated by Django 4.0.7 on 2023-02-01 15:02

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models

import api.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_remove_computeplan_failed_task_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description_address", models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()])),
                ("description_checksum", models.CharField(max_length=64)),
                ("functionrithm_address", models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()])),
                ("functionrithm_checksum", models.CharField(max_length=64)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("owner", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("channel", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["creation_date", "key"],
            },
            bases=(models.Model, api.models.utils.AssetPermissionMixin),
        ),
        migrations.CreateModel(
            name="FunctionInput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ASSET_DATA_SAMPLE", "Asset Data Sample"),
                            ("ASSET_DATA_MANAGER", "Asset Data Manager"),
                            ("ASSET_MODEL", "Asset Model"),
                        ],
                        max_length=64,
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                ("multiple", models.BooleanField(default=False)),
                ("channel", models.CharField(max_length=100)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inputs", to="api.function"
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
                "unique_together": {("function", "identifier")},
            },
        ),
        migrations.CreateModel(
            name="FunctionOutput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ASSET_MODEL", "Asset Model"), ("ASSET_PERFORMANCE", "Asset Performance")],
                        max_length=64,
                    ),
                ),
                ("multiple", models.BooleanField(default=False)),
                ("channel", models.CharField(max_length=100)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outputs", to="api.function"
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
                "unique_together": {("function", "identifier")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="algooutput",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="algooutput",
            name="algo",
        ),
        migrations.RemoveField(
            model_name="computetask",
            name="algo",
        ),
        migrations.DeleteModel(
            name="AlgoInput",
        ),
        migrations.DeleteModel(
            name="AlgoOutput",
        ),
        migrations.AddField(
            model_name="computetask",
            name="function",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compute_tasks",
                to="api.function",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="performance",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name="performances", to="api.function"
            ),
        ),
        migrations.DeleteModel(
            name="Algo",
        ),
    ]
