# Generated by Django 4.1.7 on 2023-03-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_remove_computetask_data_samples_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computetask",
            name="data_manager",
        ),
    ]
