# Generated by Django 4.1.7 on 2023-03-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_alter_datamanager_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computetask",
            name="data_samples",
        ),
        migrations.DeleteModel(
            name="TaskDataSamples",
        ),
    ]
