# Generated by Django 4.1.7 on 2023-03-06 15:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_remove_computetask_data_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamanager",
            name="channel",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
