# Generated by Django 4.0.7 on 2023-04-14 13:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_alter_datamanager_channel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="performance",
            name="identifier",
            field=models.CharField(default="performance", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="performance",
            unique_together={("compute_task", "metric", "identifier")},
        ),
    ]
