# Generated by Django 4.1.7 on 2023-04-24 15:04

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_alter_datamanager_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskprofiling",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
