# Generated by Django 4.1.7 on 2023-05-09 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_alter_performance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performance",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="performance",
            name="metric",
        ),
    ]
