# Generated by Django 4.0.7 on 2023-04-20 15:16

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_alter_performance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="performance",
            name="compute_task_output",
            field=models.ForeignKey(
                default="performance",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="performances",
                to="api.computetaskoutput",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="performance",
            unique_together={("compute_task_output", "metric")},
        ),
        migrations.RemoveField(
            model_name="performance",
            name="compute_task",
        ),
    ]
