# Generated by Django 4.2.3 on 2023-08-23 13:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_remove_metric_from_performance"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="status",
            field=models.CharField(
                choices=[
                    ("FUNCTION_STATUS_UNKONWN", "Function Status Unkonwn"),
                    ("FUNCTION_STATUS_CREATED", "Function Status Created"),
                    ("FUNCTION_STATUS_BUILDING", "Function Status Building"),
                    ("FUNCTION_STATUS_READY", "Function Status Ready"),
                    ("FUNCTION_STATUS_CANCELED", "Function Status Canceled"),
                    ("FUNCTION_STATUS_FAILED", "Function Status Failed"),
                ],
                default="FUNCTION_STATUS_UNKONWN",
                max_length=64,
            ),
            preserve_default=False,
        ),
    ]
