# Generated by Django 4.1.7 on 2023-08-23 10:03

from django.db import migrations
from django.db import models

import api.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_remove_metric_from_performance"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="logs_address",
            field=models.URLField(null=True, validators=[api.models.utils.URLValidatorWithOptionalTLD()]),
        ),
    ]
