# Generated by Django 4.1.7 on 2023-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_alter_function_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="function",
            old_name="function_address",
            new_name="archive_address",
        ),
        migrations.RenameField(
            model_name="function",
            old_name="function_checksum",
            new_name="archive_checksum",
        ),
    ]
