# Generated by Django 4.2.9 on 2024-02-13 14:38

from django.db import migrations
from django.db import models


def migrate_data(apps, schema_editor):
    status_mapping = {
        "STATUS_DOING": "STATUS_EXECUTING",
    }
    model_model = apps.get_model("api", "computetask")
    for task_instance in model_model.objects.all():
        new_status = status_mapping.get(task_instance.status_old, task_instance.status_old)
        task_instance.category = new_status
        task_instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_alter_computeplan_status_alter_computetask_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computetask",
            old_name="status",
            new_name="status_old",
        ),
        migrations.AddField(
            model_name="computetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("STATUS_WAITING_FOR_BUILDER_SLOT", "Status Waiting For Builder Slot"),
                    ("STATUS_BUILDING", "Status Building"),
                    ("STATUS_WAITING_FOR_PARENT_TASKS", "Status Waiting For Parent Tasks"),
                    ("STATUS_WAITING_FOR_EXECUTOR_SLOT", "Status Waiting For Executor Slot"),
                    ("STATUS_EXECUTING", "Status Executing"),
                    ("STATUS_DONE", "Status Done"),
                    ("STATUS_CANCELED", "Status Canceled"),
                    ("STATUS_FAILED", "Status Failed"),
                ],
                max_length=64,
                default="STATUS_DONE",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(model_name="computetask", name="status_old"),
    ]
