# Generated by Django 4.2.9 on 2024-03-22 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_alter_compute_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datamanager",
            name="type",
        ),
    ]
