# Generated by Django 4.2.10 on 2024-04-11 06:55

import django.db.models.deletion
from django.db import migrations
from django.db import models

import orchestrator.resources


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_remove_datamanager_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionProfilingStep",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("BUILD_IMAGE", orchestrator.resources.FunctionProfilingStep["BUILD_IMAGE"]),
                            ("SAVE_FUNCTION", orchestrator.resources.FunctionProfilingStep["SAVE_FUNCTION"]),
                        ],
                        max_length=100,
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profiling_steps", to="api.function"
                    ),
                ),
            ],
            options={
                "ordering": ["step"],
                "unique_together": {("function", "step")},
            },
        ),
    ]
