---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: substra-backend-delete-hook
  namespace: org-3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: substra-backend-delete-hook
  namespace: org-3
rules:
  - verbs:
      - delete
      - list
    apiGroups:
      - ""
    resources:
      - "pods"
  - verbs:
      - delete
      - list
    apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: substra-backend-delete-hook
  namespace: org-3
subjects:
  - kind: ServiceAccount
    name: substra-backend-delete-hook
    namespace: org-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: substra-backend-delete-hook
