apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: setup-service-accounts
deploy:
  kubectl:
    manifests:
      - ./serviceAccount-org-1.yaml
      - ./serviceAccount-org-2.yaml

profiles:
  - name: three-orgs
    patches:
      - op: add
        path: /deploy/kubectl/-
        value: "./serviceAccount-org-3.yaml"
