# Generated by Django 2.1.2 on 2019-08-22 11:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncomingNode",
            fields=[
                ("node_id", models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ("secret", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutgoingNode",
            fields=[
                ("node_id", models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ("secret", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
