version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/metrics-exporter"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/docker/connect-backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/docker/metrics-exporter"
    schedule:
      interval: "monthly"
