version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "docker"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "pip"
    directory: "/metrics-exporter"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "docker"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "docker"
    directory: "/docker/connect-backend"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "docker"
    directory: "/docker/metrics-exporter"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
