repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
        files: (backend|metrics_exporter|fixtures)/.+\.py

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]
        files: (backend|metrics_exporter|fixtures)/.+\.py

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: (backend|metrics_exporter|fixtures)/.+\.py
        # Checked-in Python files will be passed as positional arguments. Flake8 will always lint explicitly passed
        # arguments (the exclude section in Flake8 config file has no effect). Hence, we use pre-commit’s exclude
        # to exclude files.
        exclude: backend/orchestrator/.+_pb2(_grpc)?\.py|backend/substrapp/tests/assets\.py
        additional_dependencies:
          - pep8-naming

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args: [--ini=.bandit, -q]
