[tool.black]
force-exclude = '''
  backend/orchestrator/.+_pb2(_grpc)?\.py
| backend/substrapp/tests/assets\.py
'''
line-length = 120
target-version = ['py39']

[tool.isort]
filter_files = true
force_single_line = true
line_length = 120
profile = "black"
skip_glob = ["backend/orchestrator/*_pb2.py", "backend/orchestrator/*_pb2_grpc.py"]
src_paths = ["backend", "metrics-exporter/metrics_exporter"]
