apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: substrafoundation/substra-backend
      context: .
      docker:
        dockerfile: docker/substra-backend/Dockerfile
      sync:
        manual:
        - src: backend/manage.py
          dest: /usr/src/app/
          strip: backend/
        - src: backend/libs/**/*
          dest: /usr/src/app/libs
          strip: backend/libs/
        - src: backend/substrapp/**/*
          dest: /usr/src/app/substrapp
          strip: backend/substrapp/
        - src: backend/events/**/*
          dest: /usr/src/app/events
          strip: backend/events/
        - src: backend/backend/**/*
          dest: /usr/src/app/backend
          strip: backend/backend/
        - src: backend/node/**/*
          dest: /usr/src/app/node
          strip: backend/node/
        - src: backend/node-register/**/*
          dest: /usr/src/app/node-register
          strip: backend/node-register/
        - src: backend/users/**/*
          dest: /usr/src/app/users
          strip: backend/users/

    - image: substrafoundation/celerybeat
      context: .
      docker:
        dockerfile: docker/celerybeat/Dockerfile
      sync:
        manual:
        - src: backend/libs/**/*
          dest: /usr/src/app/libs
          strip: backend/libs/
        - src: backend/substrapp/**/*
          dest: /usr/src/app/substrapp
          strip: backend/substrapp/
        - src: backend/backend/**/*
          dest: /usr/src/app/backend
          strip: backend/backend/
        - src: backend/node/**/*
          dest: /usr/src/app/node
          strip: backend/node/
        - src: backend/users/**/*
          dest: /usr/src/app/users
          strip: backend/users/

    - image: substrafoundation/celeryworker
      context: .
      docker:
        dockerfile: docker/celeryworker/Dockerfile
      sync:
        manual:
        - src: backend/libs/**/*
          dest: /usr/src/app/libs
          strip: backend/libs/
        - src: backend/substrapp/**/*
          dest: /usr/src/app/substrapp
          strip: backend/substrapp/
        - src: backend/backend/**/*
          dest: /usr/src/app/backend
          strip: backend/backend/
        - src: backend/node/**/*
          dest: /usr/src/app/node
          strip: backend/node/
        - src: backend/users/**/*
          dest: /usr/src/app/users
          strip: backend/users/

    - image: substrafoundation/flower
      context: .
      docker:
        dockerfile: docker/flower/Dockerfile
      sync:
        manual:
        - src: backend/libs/**/*
          dest: /usr/src/app/libs
          strip: backend/libs/
        - src: backend/substrapp/**/*
          dest: /usr/src/app/substrapp
          strip: backend/substrapp/
        - src: backend/backend/**/*
          dest: /usr/src/app/backend
          strip: backend/backend/
        - src: backend/node/**/*
          dest: /usr/src/app/node
          strip: backend/node/
        - src: backend/users/**/*
          dest: /usr/src/app/users
          strip: backend/users/

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: backend-org-1
        chartPath: charts/substra-backend
        namespace: org-1
        imageStrategy:
          helm: {}
        values:
          backend.image: substrafoundation/substra-backend
          celerybeat.image: substrafoundation/celerybeat
          celeryworker.image: substrafoundation/celeryworker
          flower.image: substrafoundation/flower
        overrides:
          docker-registry:
            ingress:
              enabled: true
              hosts:
                - substra-registry.node-1.com
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
          secrets:
            fabricConfigmap: network-org-1-hlf-k8s-fabric
          backend:
            settings: dev
            defaultDomain: http://backend-org-1-substra-backend-server.org-1:8000
            ingress:
              enabled: true
              hosts:
                - { host: substra-backend.node-1.com, paths: ["/"] }
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
          organization:
            name: MyOrg1
          peer:
            host: network-org-1-peer-1-hlf-peer.org-1
            port: 7051
            mspID: MyOrg1MSP
          persistence:
            hostPath: /tmp/org-1
          incomingNodes:
            - { name: MyOrg1MSP, secret: selfSecret1 }
            - { name: MyOrg2MSP, secret: nodeSecret1w2 }
          outgoingNodes:
            - { name: MyOrg1MSP, secret: selfSecret1 }
            - { name: MyOrg2MSP, secret: nodeSecret2w1 }
          users:
            - name: "node-1"
              secret: "p@$swr0d44"
          extraEnv:
            # Should be a json list
            - name: CORS_ORIGIN_WHITELIST
              value: '["http://substra-frontend.node-1.com/"]'
            - name: DEFAULT_THROTTLE_RATES
              value: '30'

      - name: backend-org-2
        chartPath: charts/substra-backend
        namespace: org-2
        imageStrategy:
          helm: {}
        values:
          backend.image: substrafoundation/substra-backend
          celerybeat.image: substrafoundation/celerybeat
          celeryworker.image: substrafoundation/celeryworker
          flower.image: substrafoundation/flower
        overrides:
          docker-registry:
            ingress:
              enabled: true
              hosts:
                - substra-registry.node-2.com
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
          secrets:
            fabricConfigmap: network-org-2-hlf-k8s-fabric
          backend:
            settings: dev
            defaultDomain: http://backend-org-2-substra-backend-server.org-2:8000
            ingress:
              enabled: true
              hosts:
                - { host: substra-backend.node-2.com, paths: ["/"] }
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
          organization:
            name: MyOrg2
          peer:
            host: network-org-2-peer-1-hlf-peer.org-2
            port: 7051
            mspID: MyOrg2MSP
          persistence:
            hostPath: /tmp/org-2
          incomingNodes:
            - { name: MyOrg1MSP, secret: nodeSecret2w1 }
            - { name: MyOrg2MSP, secret: selfSecret2 }
          outgoingNodes:
            - { name: MyOrg1MSP, secret: nodeSecret1w2 }
            - { name: MyOrg2MSP, secret: selfSecret2 }
          users:
            - name: "node-2"
              secret: "p@$swr0d45"
          extraEnv:
            # Should be a json list
            - name: CORS_ORIGIN_WHITELIST
              value: '["http://substra-frontend.node-2.com/"]'
            - name: DEFAULT_THROTTLE_RATES
              value: '30'

profiles:
  - name: prod
    patches:
      - op: replace
        path: /deploy/helm/releases/0/overrides/backend/settings
        value: prod
      - op: replace
        path: /deploy/helm/releases/1/overrides/backend/settings
        value: prod
