apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: substrafoundation/substra-backend
      context: .
      docker:
        dockerfile: docker/substra-backend/Dockerfile
      sync:
        manual:
        - src: backend/manage.py
          dest: /usr/src/app/
          strip: backend/
        - src: backend/libs/**/*
          dest: /usr/src/app/libs
          strip: backend/libs/
        - src: backend/substrapp/**/*
          dest: /usr/src/app/substrapp
          strip: backend/substrapp/
        - src: backend/events/**/*
          dest: /usr/src/app/events
          strip: backend/events/
        - src: backend/backend/**/*
          dest: /usr/src/app/backend
          strip: backend/backend/
        - src: backend/node/**/*
          dest: /usr/src/app/node
          strip: backend/node/
        - src: backend/node_register/**/*
          dest: /usr/src/app/node_register
          strip: backend/node_register/
        - src: backend/users/**/*
          dest: /usr/src/app/users
          strip: backend/users/

deploy:
  statusCheckDeadlineSeconds: 600
  helm:
    releases:
      - name: backend-org-1
        chartPath: charts/substra-backend
        namespace: org-1
        valuesFiles: [ examples/values/backend-org-1.yaml ]
        setValues: { _: _ } # to support profiles
        imageStrategy:
          helm: {}
        values:
          backend.image: substrafoundation/substra-backend
          celerybeat.image: substrafoundation/substra-backend
          celeryworker.image: substrafoundation/substra-backend

      - name: backend-org-2
        chartPath: charts/substra-backend
        namespace: org-2
        valuesFiles: [ examples/values/backend-org-2.yaml ]
        setValues: { _: _ } # to support profiles
        imageStrategy:
          helm: {}
        values:
          backend.image: substrafoundation/substra-backend
          celerybeat.image: substrafoundation/substra-backend
          celeryworker.image: substrafoundation/substra-backend
        skipBuildDependencies: true # deps already built by other org-1 release

    flags:
      install: ["--create-namespace"]
  kubectl:
    manifests:
      - examples/values/serviceAccounts/serviceAccount-org-1.yaml
      - examples/values/serviceAccounts/serviceAccount-org-2.yaml
      - examples/secrets/configmap-orchestrator-tls-org-1-cacert.yaml
      - examples/secrets/secret-orchestrator-tls-org-1-client-pair.yaml
      - examples/secrets/configmap-orchestrator-tls-org-2-cacert.yaml
      - examples/secrets/secret-orchestrator-tls-org-2-client-pair.yaml

profiles:
  - name: prod
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues/backend.settings
        value: prod
      - op: add
        path: /deploy/helm/releases/1/setValues/backend.settings
        value: prod
  - name: nodeps
    patches:
      - op: add
        path: /deploy/helm/releases/0/skipBuildDependencies
        value: true
  - name: single-org
    patches:
      - op: remove
        path: /deploy/helm/releases/1
      - op: remove
        path: /deploy/kubectl/manifests/5
      - op: remove
        path: /deploy/kubectl/manifests/4
      - op: remove
        path: /deploy/kubectl/manifests/1
  - name: distributed
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValues/orchestrator.host
        value: owkin-orchestrator-org-2-server.org-2.svc.cluster.local
      - op: add
        path: /deploy/helm/releases/1/setValues/orchestrator.rabbitmq.host
        value: owkin-orchestrator-org-2-rabbitmq.org-2.svc.cluster.local
  - name: persist-db
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues/postgresql.persistence.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValues/postgresql.persistence.enabled
        value: true
  - name: spread-workers
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value: [ examples/values/backend-org-1.yaml, examples/values/spread-workers.yaml ]
      - op: replace
        path: /deploy/helm/releases/1/valuesFiles
        value: [ examples/values/backend-org-2.yaml, examples/values/spread-workers.yaml ]
  - name: add-worker-server-node-selectors
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value: [ examples/values/backend-org-1.yaml, examples/values/add-worker-server-node-selectors.yaml ]
      - op: replace
        path: /deploy/helm/releases/1/valuesFiles
        value: [ examples/values/backend-org-2.yaml, examples/values/add-worker-server-node-selectors.yaml ]
