apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: substrafoundation/substra-backend
      context: .
      docker:
        dockerfile: docker/substra-backend/Dockerfile

    - image: substrafoundation/celerybeat
      context: .
      docker:
        dockerfile: docker/celerybeat/Dockerfile

    - image: substrafoundation/celeryworker
      context: .
      docker:
        dockerfile: docker/celeryworker/Dockerfile

    - image: substrafoundation/flower
      context: .
      docker:
        dockerfile: docker/flower/Dockerfile

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: backend-org-1
        chartPath: charts/substra-backend
        namespace: org-1
        imageStrategy:
          helm: {}
        values:
          backend.image: substrafoundation/substra-backend
          celerybeat.image: substrafoundation/celerybeat
          celeryworker.image: substrafoundation/celeryworker
          flower.image: substrafoundation/flower
        overrides:
          secrets:
            fabricConfigmap: network-org-1-hlf-k8s-fabric
          backend:
            settings: dev
            defaultDomain: http://substra-backend.node-1.com
            ingress:
              enabled: true
              hosts:
                - { host: substra-backend.node-1.com, paths: ["/"] }
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
          organization:
            name: MyOrg1
          peer:
            host: network-org-1-peer-1.org-1
            port: 7051
            mspID: MyOrg1MSP
          persistence:
            hostPath: /tmp/org-1
          incomingNodes:
            - { name: MyOrg1MSP, secret: selfSecret1 }
            - { name: MyOrg2MSP, secret: nodeSecret1w2 }
          outgoingNodes:
            - { name: MyOrg1MSP, secret: selfSecret1 }
            - { name: MyOrg2MSP, secret: nodeSecret2w1 }
          users:
            - name: "node-1"
              secret: "p@$swr0d44"

      - name: backend-org-2
        chartPath: charts/substra-backend
        namespace: org-2
        imageStrategy:
          helm: {}
        values:
          backend.image: substrafoundation/substra-backend
          celerybeat.image: substrafoundation/celerybeat
          celeryworker.image: substrafoundation/celeryworker
          flower.image: substrafoundation/flower
        overrides:
          secrets:
            fabricConfigmap: network-org-2-hlf-k8s-fabric
          backend:
            settings: dev
            defaultDomain: http://substra-backend.node-2.com
            ingress:
              enabled: true
              hosts:
                - { host: substra-backend.node-2.com, paths: ["/"] }
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
          organization:
            name: MyOrg2
          peer:
            host: network-org-2-peer-1.org-2
            port: 7051
            mspID: MyOrg2MSP
          persistence:
            hostPath: /tmp/org-2
          incomingNodes:
            - { name: MyOrg1MSP, secret: nodeSecret2w1 }
            - { name: MyOrg2MSP, secret: selfSecret2 }
          outgoingNodes:
            - { name: MyOrg1MSP, secret: nodeSecret1w2 }
            - { name: MyOrg2MSP, secret: selfSecret2 }
          users:
            - name: "node-2"
              secret: "p@$swr0d45"

profiles:
  - name: prod
    patches:
      - op: replace
        path: /deploy/helm/releases/0/overrides/backend/settings
        value: prod
      - op: replace
        path: /deploy/helm/releases/1/overrides/backend/settings
        value: prod
