# Generated by Django 2.0.5 on 2018-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('features', models.FileField(upload_to='')),
                ('labels', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DataOpener',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=24)),
                ('script', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('description', models.FileField(upload_to='')),
                ('metrics', models.FileField(upload_to='')),
            ],
        ),
    ]
