# Generated by Django 2.0.5 on 2018-07-12 16:36

from django.db import migrations, models
import substrapp.models.algo
import substrapp.models.challenge
import substrapp.models.data
import substrapp.models.dataset
import substrapp.models.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=substrapp.models.algo.upload_to)),
                ('description', models.FileField(upload_to=substrapp.models.algo.upload_to)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('description', models.FileField(upload_to=substrapp.models.challenge.upload_to)),
                ('metrics', models.FileField(upload_to=substrapp.models.challenge.upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=substrapp.models.data.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=24)),
                ('data_opener', models.FileField(upload_to=substrapp.models.dataset.upload_to)),
                ('description', models.FileField(upload_to=substrapp.models.dataset.upload_to)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=substrapp.models.model.upload_to)),
            ],
        ),
    ]
