# Generated by Django 2.0.5 on 2018-05-17 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 13, 12, 17, 403798, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 13, 12, 30, 392450, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
