# Generated by Django 2.1 on 2018-08-31 13:39

from django.db import migrations, models
import substrapp.models.challenge


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0002_auto_20180821_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=substrapp.models.challenge.upload_to),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='metrics',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=substrapp.models.challenge.upload_to),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
