# Generated by Django 2.0.5 on 2018-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0002_auto_20180517_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('algo', models.FileField(upload_to='')),
            ],
        ),
    ]
