# Generated by Django 2.1 on 2018-09-11 13:34

from django.db import migrations, models
import substrapp.models.model


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0003_auto_20180831_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=substrapp.models.model.upload_to),
        ),
    ]
