# Generated by Django 2.1.2 on 2018-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0003_auto_20180831_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
        migrations.AddField(
            model_name='data',
            name='path',
            field=models.FilePathField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
