# Generated by Django 2.1.2 on 2019-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0003_auto_20180831_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
