# Generated by Django 2.1.2 on 2018-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0003_auto_20180831_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
        migrations.AddField(
            model_name='data',
            name='path',
            field=models.FilePathField(blank=True, max_length=500, null=True),
        ),
    ]
