# Generated by Django 2.1.2 on 2018-11-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0004_auto_20181114_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='path',
            field=models.FilePathField(blank=True, max_length=500, null=True),
        ),
    ]
