sequenceDiagram
    Admin user->>+Connect GUI: Request reset password of user1 (creator)
    Connect GUI->>+Connect Backend: POST on /users/user1/reset_password/
    Note over Connect Backend: Generating jwt token <br> based on user1 password <br> hash and backend secret
    Connect Backend->>-Connect GUI: Reset token
    Connect GUI->>-Admin user: Copy reset link to clipboard
