sequenceDiagram
    Unauthenticated user1 ->>+ Connect GUI: Use reset link given by admin
    Connect GUI ->>+ Connect Backend: GET on /users/user1/verify_token/?token={reset_token}

    Note over Connect Backend: Try to decode jwt token <br> based on user1 password <br> hash and backend secret

    alt Reset token is valid
        Connect Backend ->> Connect GUI: http 200 OK
        Connect GUI ->> Unauthenticated user1: Display reset password page
        Unauthenticated user1 ->>+ Connect GUI: Enters new password
        Connect GUI ->>+ Connect Backend: POST on /users/user1/set_password/
        Note over Connect Backend: Try to decode jwt token <br> based on user1 password <br> hash and backend secret
        Connect Backend ->> Connect GUI: http 200 OK

    else Reset token not valid
        Connect Backend ->>- Connect GUI: http 401 Unauthorized
        Connect GUI ->>- Unauthenticated user1: Display login page
    end
