sequenceDiagram
    Admin user->>+Substra GUI: Request reset password of user1 (creator)
    Substra GUI->>+Substra Backend: POST on /users/user1/reset_password/
    Note over Substra Backend: Generating jwt token <br> based on user1 password <br> hash and backend secret
    Substra Backend->>-Substra GUI: Reset token
    Substra GUI->>-Admin user: Copy reset link to clipboard
