sequenceDiagram
    Unauthenticated user1 ->>+ Substra GUI: Use reset link given by admin
    Substra GUI ->>+ Substra Backend: GET on /users/user1/verify_token/?token={reset_token}

    Note over Substra Backend: Try to decode jwt token <br> based on user1 password <br> hash and backend secret

    alt Reset token is valid
        Substra Backend ->> Substra GUI: http 200 OK
        Substra GUI ->> Unauthenticated user1: Display reset password page
        Unauthenticated user1 ->>+ Substra GUI: Enters new password
        Substra GUI ->>+ Substra Backend: POST on /users/user1/set_password/
        Note over Substra Backend: Try to decode jwt token <br> based on user1 password <br> hash and backend secret
        Substra Backend ->> Substra GUI: http 200 OK

    else Reset token not valid
        Substra Backend ->>- Substra GUI: http 401 Unauthorized
        Substra GUI ->>- Unauthenticated user1: Display login page
    end
