apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org-3
  namespace: org-3
spec:
  secretName: orchestrator-tls-client-pair
  duration: 2160h
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - MyOrg3MSP
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - substra-backend.org-1.com
  issuerRef:
    name: substra-issuer
    kind: ClusterIssuer
