apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
  namespace: harbor
spec:
  secretName: harbor-registry-tls
  duration: 2160h
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - MyOrg2MSP
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - registry.org-2.com
  issuerRef:
    name: substra-issuer
    kind: ClusterIssuer
