apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: setup-secrets
deploy:
  kubectl:
    manifests:
      - ./secret-orchestrator-tls-org-1-client-pair.yaml
      - ./secret-orchestrator-tls-org-2-client-pair.yaml
      - ./secret-oidc-org-1.yaml

profiles:
  - name: temp-three-orgs
    patches:
      - op: add
        path: /deploy/kubectl/manifests/-
        value:
          - ./secret-orchestrator-tls-org-3-client-pair.yaml
