apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: setup-secrets
deploy:
  kubectl:
    manifests:
        - ./secret-orchestrator-tls-org-1-client-pair.yaml
        - ./secret-orchestrator-tls-org-2-client-pair.yaml