.PHONY: doc
doc:
	# There is no release of the readme-generator-for-helm tool on the repo so we target an arbitrary commit
	npx https://github.com/bitnami-labs/readme-generator-for-helm/tree/3300343a6cd1c9cd86d13b04d8c85a7415cb849e -v substra-backend/values.yaml -r substra-backend/README.md

