# Generated by Django 4.0 on 2022-01-11 13:46

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models

import localrep.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algo",
            fields=[
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.IntegerField(
                        choices=[(0, "ALGO_UNKNOWN"), (1, "ALGO_SIMPLE"), (2, "ALGO_AGGREGATE"), (3, "ALGO_COMPOSITE")]
                    ),
                ),
                (
                    "description_address",
                    models.URLField(validators=[localrep.models.utils.URLValidatorWithOptionalTLD()]),
                ),
                ("description_checksum", models.CharField(max_length=64)),
                (
                    "algorithm_address",
                    models.URLField(validators=[localrep.models.utils.URLValidatorWithOptionalTLD()]),
                ),
                ("algorithm_checksum", models.CharField(max_length=64)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("owner", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("channel", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("asset_key", models.CharField(max_length=100)),
                (
                    "asset_kind",
                    models.IntegerField(
                        choices=[
                            (0, "ASSET_UNKNOWN"),
                            (1, "ASSET_NODE"),
                            (2, "ASSET_METRIC"),
                            (3, "ASSET_DATA_SAMPLE"),
                            (4, "ASSET_DATA_MANAGER"),
                            (5, "ASSET_ALGO"),
                            (6, "ASSET_COMPUTE_TASK"),
                            (7, "ASSET_COMPUTE_PLAN"),
                            (8, "ASSET_MODEL"),
                            (9, "ASSET_PERFORMANCE"),
                            (10, "ASSET_FAILURE_REPORT"),
                        ]
                    ),
                ),
                (
                    "event_kind",
                    models.IntegerField(
                        choices=[
                            (0, "EVENT_UNKNOWN"),
                            (1, "EVENT_ASSET_CREATED"),
                            (2, "EVENT_ASSET_UPDATED"),
                            (3, "EVENT_ASSET_DISABLED"),
                        ]
                    ),
                ),
                ("channel", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("metadata", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "description_address",
                    models.URLField(validators=[localrep.models.utils.URLValidatorWithOptionalTLD()]),
                ),
                ("description_checksum", models.CharField(max_length=64)),
                ("metric_address", models.URLField(validators=[localrep.models.utils.URLValidatorWithOptionalTLD()])),
                ("metric_checksum", models.CharField(max_length=64)),
                ("permissions_download_public", models.BooleanField()),
                (
                    "permissions_download_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("permissions_process_public", models.BooleanField()),
                (
                    "permissions_process_authorized_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), size=100),
                ),
                ("owner", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField()),
                ("metadata", models.JSONField()),
                ("channel", models.CharField(max_length=100)),
            ],
        ),
    ]
