# Generated by Django 4.0.1 on 2022-02-21 10:44

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("localrep", "0003_computeplan_computetask"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("performance_value", models.FloatField()),
                ("creation_date", models.DateTimeField()),
                ("channel", models.CharField(max_length=100)),
                (
                    "compute_task_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="performances",
                        to="localrep.computetask",
                    ),
                ),
                (
                    "metric_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="performances",
                        to="localrep.metric",
                    ),
                ),
            ],
            options={
                "unique_together": {("compute_task_key", "metric_key")},
            },
        ),
    ]
