# Generated by Django 4.0.6 on 2022-07-22 12:21

from django.db import migrations

import localrep


def set_cancelation_date_on_compute_plans(apps, schema_editor):
    ComputePlan = apps.get_model("localrep", "ComputePlan")  # noqa: N806
    for plan in ComputePlan.objects.filter(
        status=localrep.models.ComputePlan.Status.PLAN_STATUS_CANCELED,
    ):
        plan.cancelation_date = plan.creation_date
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("localrep", "0025_computeplan_cancelation_date"),
    ]

    operations = [
        migrations.RunPython(set_cancelation_date_on_compute_plans),
    ]
