# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0corchestrator\"8\n\x0b\x41\x64\x64ressable\x12\x10\n\x08\x63hecksum\x18\x01 \x01(\t\x12\x17\n\x0fstorage_address\x18\x02 \x01(\t\"d\n\x0bPermissions\x12)\n\x07process\x18\x01 \x01(\x0b\x32\x18.orchestrator.Permission\x12*\n\x08\x64ownload\x18\x02 \x01(\x0b\x32\x18.orchestrator.Permission\"4\n\nPermission\x12\x0e\n\x06public\x18\x01 \x01(\x08\x12\x16\n\x0e\x61uthorized_ids\x18\x02 \x03(\t\"8\n\x0eNewPermissions\x12\x0e\n\x06public\x18\x01 \x01(\x08\x12\x16\n\x0e\x61uthorized_ids\x18\x02 \x03(\t*\xa4\x02\n\tAssetKind\x12\x11\n\rASSET_UNKNOWN\x10\x00\x12\x16\n\x12\x41SSET_ORGANIZATION\x10\x01\x12\x15\n\x11\x41SSET_DATA_SAMPLE\x10\x03\x12\x16\n\x12\x41SSET_DATA_MANAGER\x10\x04\x12\x12\n\x0e\x41SSET_FUNCTION\x10\x05\x12\x16\n\x12\x41SSET_COMPUTE_TASK\x10\x06\x12\x16\n\x12\x41SSET_COMPUTE_PLAN\x10\x07\x12\x0f\n\x0b\x41SSET_MODEL\x10\x08\x12\x15\n\x11\x41SSET_PERFORMANCE\x10\t\x12\x18\n\x14\x41SSET_FAILURE_REPORT\x10\n\x12#\n\x1f\x41SSET_COMPUTE_TASK_OUTPUT_ASSET\x10\x0b\"\x04\x08\x02\x10\x02*\x0c\x41SSET_METRIC*;\n\tSortOrder\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\r\n\tASCENDING\x10\x01\x12\x0e\n\nDESCENDING\x10\x02\x42+Z)github.com/substra/orchestrator/lib/assetb\x06proto3')

_ASSETKIND = DESCRIPTOR.enum_types_by_name['AssetKind']
AssetKind = enum_type_wrapper.EnumTypeWrapper(_ASSETKIND)
_SORTORDER = DESCRIPTOR.enum_types_by_name['SortOrder']
SortOrder = enum_type_wrapper.EnumTypeWrapper(_SORTORDER)
ASSET_UNKNOWN = 0
ASSET_ORGANIZATION = 1
ASSET_DATA_SAMPLE = 3
ASSET_DATA_MANAGER = 4
ASSET_FUNCTION = 5
ASSET_COMPUTE_TASK = 6
ASSET_COMPUTE_PLAN = 7
ASSET_MODEL = 8
ASSET_PERFORMANCE = 9
ASSET_FAILURE_REPORT = 10
ASSET_COMPUTE_TASK_OUTPUT_ASSET = 11
UNSPECIFIED = 0
ASCENDING = 1
DESCENDING = 2


_ADDRESSABLE = DESCRIPTOR.message_types_by_name['Addressable']
_PERMISSIONS = DESCRIPTOR.message_types_by_name['Permissions']
_PERMISSION = DESCRIPTOR.message_types_by_name['Permission']
_NEWPERMISSIONS = DESCRIPTOR.message_types_by_name['NewPermissions']
Addressable = _reflection.GeneratedProtocolMessageType('Addressable', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSABLE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.Addressable)
  })
_sym_db.RegisterMessage(Addressable)

Permissions = _reflection.GeneratedProtocolMessageType('Permissions', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONS,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.Permissions)
  })
_sym_db.RegisterMessage(Permissions)

Permission = _reflection.GeneratedProtocolMessageType('Permission', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.Permission)
  })
_sym_db.RegisterMessage(Permission)

NewPermissions = _reflection.GeneratedProtocolMessageType('NewPermissions', (_message.Message,), {
  'DESCRIPTOR' : _NEWPERMISSIONS,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.NewPermissions)
  })
_sym_db.RegisterMessage(NewPermissions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/substra/orchestrator/lib/asset'
  _ASSETKIND._serialized_start=303
  _ASSETKIND._serialized_end=595
  _SORTORDER._serialized_start=597
  _SORTORDER._serialized_end=656
  _ADDRESSABLE._serialized_start=30
  _ADDRESSABLE._serialized_end=86
  _PERMISSIONS._serialized_start=88
  _PERMISSIONS._serialized_end=188
  _PERMISSION._serialized_start=190
  _PERMISSION._serialized_end=242
  _NEWPERMISSIONS._serialized_start=244
  _NEWPERMISSIONS._serialized_end=300
# @@protoc_insertion_point(module_scope)
