# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x0corchestrator\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x02\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tasset_key\x18\x02 \x01(\t\x12+\n\nasset_kind\x18\x03 \x01(\x0e\x32\x17.orchestrator.AssetKind\x12+\n\nevent_kind\x18\x04 \x01(\x0e\x32\x17.orchestrator.EventKind\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x08metadata\x18\x12 \x03(\x0b\x32!.orchestrator.Event.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x90\x01\n\x10QueryEventsParam\x12\x12\n\npage_token\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\r\x12.\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\x1e.orchestrator.EventQueryFilter\x12%\n\x04sort\x18\x04 \x01(\x0e\x32\x17.orchestrator.SortOrder\"\xc4\x02\n\x10\x45ventQueryFilter\x12\x11\n\tasset_key\x18\x01 \x01(\t\x12+\n\nasset_kind\x18\x02 \x01(\x0e\x32\x17.orchestrator.AssetKind\x12+\n\nevent_kind\x18\x03 \x01(\x0e\x32\x17.orchestrator.EventKind\x12>\n\x08metadata\x18\x04 \x03(\x0b\x32,.orchestrator.EventQueryFilter.MetadataEntry\x12)\n\x05start\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x13QueryEventsResponse\x12#\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x13.orchestrator.Event\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t*j\n\tEventKind\x12\x11\n\rEVENT_UNKNOWN\x10\x00\x12\x17\n\x13\x45VENT_ASSET_CREATED\x10\x01\x12\x17\n\x13\x45VENT_ASSET_UPDATED\x10\x02\x12\x18\n\x14\x45VENT_ASSET_DISABLED\x10\x03\x32`\n\x0c\x45ventService\x12P\n\x0bQueryEvents\x12\x1e.orchestrator.QueryEventsParam\x1a!.orchestrator.QueryEventsResponseB)Z\'github.com/owkin/orchestrator/lib/assetb\x06proto3')

_EVENTKIND = DESCRIPTOR.enum_types_by_name['EventKind']
EventKind = enum_type_wrapper.EnumTypeWrapper(_EVENTKIND)
EVENT_UNKNOWN = 0
EVENT_ASSET_CREATED = 1
EVENT_ASSET_UPDATED = 2
EVENT_ASSET_DISABLED = 3


_EVENT = DESCRIPTOR.message_types_by_name['Event']
_EVENT_METADATAENTRY = _EVENT.nested_types_by_name['MetadataEntry']
_QUERYEVENTSPARAM = DESCRIPTOR.message_types_by_name['QueryEventsParam']
_EVENTQUERYFILTER = DESCRIPTOR.message_types_by_name['EventQueryFilter']
_EVENTQUERYFILTER_METADATAENTRY = _EVENTQUERYFILTER.nested_types_by_name['MetadataEntry']
_QUERYEVENTSRESPONSE = DESCRIPTOR.message_types_by_name['QueryEventsResponse']
Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_METADATAENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:orchestrator.Event.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.MetadataEntry)

QueryEventsParam = _reflection.GeneratedProtocolMessageType('QueryEventsParam', (_message.Message,), {
  'DESCRIPTOR' : _QUERYEVENTSPARAM,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.QueryEventsParam)
  })
_sym_db.RegisterMessage(QueryEventsParam)

EventQueryFilter = _reflection.GeneratedProtocolMessageType('EventQueryFilter', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTQUERYFILTER_METADATAENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:orchestrator.EventQueryFilter.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _EVENTQUERYFILTER,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.EventQueryFilter)
  })
_sym_db.RegisterMessage(EventQueryFilter)
_sym_db.RegisterMessage(EventQueryFilter.MetadataEntry)

QueryEventsResponse = _reflection.GeneratedProtocolMessageType('QueryEventsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYEVENTSRESPONSE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.QueryEventsResponse)
  })
_sym_db.RegisterMessage(QueryEventsResponse)

_EVENTSERVICE = DESCRIPTOR.services_by_name['EventService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/owkin/orchestrator/lib/asset'
  _EVENT_METADATAENTRY._options = None
  _EVENT_METADATAENTRY._serialized_options = b'8\001'
  _EVENTQUERYFILTER_METADATAENTRY._options = None
  _EVENTQUERYFILTER_METADATAENTRY._serialized_options = b'8\001'
  _EVENTKIND._serialized_start=932
  _EVENTKIND._serialized_end=1038
  _EVENT._serialized_start=77
  _EVENT._serialized_end=371
  _EVENT_METADATAENTRY._serialized_start=324
  _EVENT_METADATAENTRY._serialized_end=371
  _QUERYEVENTSPARAM._serialized_start=374
  _QUERYEVENTSPARAM._serialized_end=518
  _EVENTQUERYFILTER._serialized_start=521
  _EVENTQUERYFILTER._serialized_end=845
  _EVENTQUERYFILTER_METADATAENTRY._serialized_start=324
  _EVENTQUERYFILTER_METADATAENTRY._serialized_end=371
  _QUERYEVENTSRESPONSE._serialized_start=847
  _QUERYEVENTSRESPONSE._serialized_end=930
  _EVENTSERVICE._serialized_start=1040
  _EVENTSERVICE._serialized_end=1136
# @@protoc_insertion_point(module_scope)
