# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='orchestrator',
  syntax='proto3',
  serialized_options=b'Z\'github.com/owkin/orchestrator/lib/asset',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nnode.proto\x12\x0corchestrator\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x31\n\rcreation_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"8\n\x13GetAllNodesResponse\x12!\n\x05nodes\x18\x01 \x03(\x0b\x32\x12.orchestrator.Node\"\x13\n\x11RegisterNodeParam\"\x12\n\x10GetAllNodesParam2\xa4\x01\n\x0bNodeService\x12\x43\n\x0cRegisterNode\x12\x1f.orchestrator.RegisterNodeParam\x1a\x12.orchestrator.Node\x12P\n\x0bGetAllNodes\x12\x1e.orchestrator.GetAllNodesParam\x1a!.orchestrator.GetAllNodesResponseB)Z\'github.com/owkin/orchestrator/lib/assetb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='orchestrator.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orchestrator.Node.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_date', full_name='orchestrator.Node.creation_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=130,
)


_GETALLNODESRESPONSE = _descriptor.Descriptor(
  name='GetAllNodesResponse',
  full_name='orchestrator.GetAllNodesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='orchestrator.GetAllNodesResponse.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=188,
)


_REGISTERNODEPARAM = _descriptor.Descriptor(
  name='RegisterNodeParam',
  full_name='orchestrator.RegisterNodeParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=209,
)


_GETALLNODESPARAM = _descriptor.Descriptor(
  name='GetAllNodesParam',
  full_name='orchestrator.GetAllNodesParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=229,
)

_NODE.fields_by_name['creation_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETALLNODESRESPONSE.fields_by_name['nodes'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['GetAllNodesResponse'] = _GETALLNODESRESPONSE
DESCRIPTOR.message_types_by_name['RegisterNodeParam'] = _REGISTERNODEPARAM
DESCRIPTOR.message_types_by_name['GetAllNodesParam'] = _GETALLNODESPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.Node)
  })
_sym_db.RegisterMessage(Node)

GetAllNodesResponse = _reflection.GeneratedProtocolMessageType('GetAllNodesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLNODESRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.GetAllNodesResponse)
  })
_sym_db.RegisterMessage(GetAllNodesResponse)

RegisterNodeParam = _reflection.GeneratedProtocolMessageType('RegisterNodeParam', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERNODEPARAM,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.RegisterNodeParam)
  })
_sym_db.RegisterMessage(RegisterNodeParam)

GetAllNodesParam = _reflection.GeneratedProtocolMessageType('GetAllNodesParam', (_message.Message,), {
  'DESCRIPTOR' : _GETALLNODESPARAM,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.GetAllNodesParam)
  })
_sym_db.RegisterMessage(GetAllNodesParam)


DESCRIPTOR._options = None

_NODESERVICE = _descriptor.ServiceDescriptor(
  name='NodeService',
  full_name='orchestrator.NodeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=232,
  serialized_end=396,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNode',
    full_name='orchestrator.NodeService.RegisterNode',
    index=0,
    containing_service=None,
    input_type=_REGISTERNODEPARAM,
    output_type=_NODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllNodes',
    full_name='orchestrator.NodeService.GetAllNodes',
    index=1,
    containing_service=None,
    input_type=_GETALLNODESPARAM,
    output_type=_GETALLNODESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODESERVICE)

DESCRIPTOR.services_by_name['NodeService'] = _NODESERVICE

# @@protoc_insertion_point(module_scope)
