# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12organization.proto\x12\x0corchestrator\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n\x0cOrganization\x12\n\n\x02id\x18\x01 \x01(\t\x12\x31\n\rcreation_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"P\n\x1bGetAllOrganizationsResponse\x12\x31\n\rorganizations\x18\x01 \x03(\x0b\x32\x1a.orchestrator.Organization\"\x1b\n\x19RegisterOrganizationParam\"\x1a\n\x18GetAllOrganizationsParam2\xdc\x01\n\x13OrganizationService\x12[\n\x14RegisterOrganization\x12\'.orchestrator.RegisterOrganizationParam\x1a\x1a.orchestrator.Organization\x12h\n\x13GetAllOrganizations\x12&.orchestrator.GetAllOrganizationsParam\x1a).orchestrator.GetAllOrganizationsResponseB)Z\'github.com/owkin/orchestrator/lib/assetb\x06proto3')



_ORGANIZATION = DESCRIPTOR.message_types_by_name['Organization']
_GETALLORGANIZATIONSRESPONSE = DESCRIPTOR.message_types_by_name['GetAllOrganizationsResponse']
_REGISTERORGANIZATIONPARAM = DESCRIPTOR.message_types_by_name['RegisterOrganizationParam']
_GETALLORGANIZATIONSPARAM = DESCRIPTOR.message_types_by_name['GetAllOrganizationsParam']
Organization = _reflection.GeneratedProtocolMessageType('Organization', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATION,
  '__module__' : 'organization_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.Organization)
  })
_sym_db.RegisterMessage(Organization)

GetAllOrganizationsResponse = _reflection.GeneratedProtocolMessageType('GetAllOrganizationsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLORGANIZATIONSRESPONSE,
  '__module__' : 'organization_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.GetAllOrganizationsResponse)
  })
_sym_db.RegisterMessage(GetAllOrganizationsResponse)

RegisterOrganizationParam = _reflection.GeneratedProtocolMessageType('RegisterOrganizationParam', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERORGANIZATIONPARAM,
  '__module__' : 'organization_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.RegisterOrganizationParam)
  })
_sym_db.RegisterMessage(RegisterOrganizationParam)

GetAllOrganizationsParam = _reflection.GeneratedProtocolMessageType('GetAllOrganizationsParam', (_message.Message,), {
  'DESCRIPTOR' : _GETALLORGANIZATIONSPARAM,
  '__module__' : 'organization_pb2'
  # @@protoc_insertion_point(class_scope:orchestrator.GetAllOrganizationsParam)
  })
_sym_db.RegisterMessage(GetAllOrganizationsParam)

_ORGANIZATIONSERVICE = DESCRIPTOR.services_by_name['OrganizationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/owkin/orchestrator/lib/asset'
  _ORGANIZATION._serialized_start=69
  _ORGANIZATION._serialized_end=146
  _GETALLORGANIZATIONSRESPONSE._serialized_start=148
  _GETALLORGANIZATIONSRESPONSE._serialized_end=228
  _REGISTERORGANIZATIONPARAM._serialized_start=230
  _REGISTERORGANIZATIONPARAM._serialized_end=257
  _GETALLORGANIZATIONSPARAM._serialized_start=259
  _GETALLORGANIZATIONSPARAM._serialized_end=285
  _ORGANIZATIONSERVICE._serialized_start=288
  _ORGANIZATIONSERVICE._serialized_end=508
# @@protoc_insertion_point(module_scope)
