"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ProfilingStep(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_FIELD_NUMBER: builtins.int
    ASSET_KEY_FIELD_NUMBER: builtins.int
    STEP_FIELD_NUMBER: builtins.int
    duration: builtins.int
    asset_key: builtins.str
    step: builtins.str
    def __init__(
        self,
        *,
        duration: builtins.int = ...,
        asset_key: builtins.str = ...,
        step: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset_key", b"asset_key", "duration", b"duration", "step", b"step"]) -> None: ...

global___ProfilingStep = ProfilingStep
