apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
data:
  DATABASE_DATABASE: !!str {{ .Values.database.auth.database }}
  DATABASE_HOSTNAME: !!str {{ include "substra-backend.database.host" . }}
  DATABASE_PORT: !!str {{ .Values.database.port }}
