apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-rabbitmq
  labels:
  {{- include "substra.labels" . | nindent 4 }}
data:
  CELERY_BROKER_USER: {{ .Values.rabbitmq.auth.username }}
  CELERY_BROKER_HOST: {{ default (include "rabbitmq.serviceName" .) .Values.rabbitmq.host }}
  CELERY_BROKER_PORT: {{ .Values.rabbitmq.service.ports.amqp | quote }}
