apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
data:
  BACKEND_DB_NAME: {{ .Values.postgresql.auth.database }}
  BACKEND_DB_USER: {{ .Values.postgresql.auth.username }}
  DATABASE_HOST: {{ template "postgresql.serviceName" . }}
