apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
data:
  POSTGRESQL_DATABASE: {{ .Values.postgresql.auth.database }}
  POSTGRESQL_HOSTNAME: {{ template "substra-backend.postgresql.host" . }}
  POSTGRESQL_PORT: {{ .Values.postgresql.auth.port }}
