apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substra.fullname" . }}-orchestrator
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}
data:
  ORCHESTRATOR_HOST: {{ .Values.orchestrator.host | quote }}
  ORCHESTRATOR_PORT: {{ .Values.orchestrator.port | quote }}
  ORCHESTRATOR_TLS_ENABLED: {{ .Values.orchestrator.tls.enabled |quote }}
  ORCHESTRATOR_MTLS_ENABLED: {{ and .Values.orchestrator.tls.enabled .Values.orchestrator.tls.mtls.enabled | quote }}
  ORCHESTRATOR_TLS_SERVER_CACERT_PATH: "/var/substra/orchestrator/tls/server/ca.crt"
  ORCHESTRATOR_TLS_CLIENT_CERT_PATH: "/var/substra/orchestrator/tls/client/tls.crt"
  ORCHESTRATOR_TLS_CLIENT_KEY_PATH: "/var/substra/orchestrator/tls/client/tls.key"

  # RabbitMQ
  ORCHESTRATOR_RABBITMQ_HOST: {{ .Values.orchestrator.rabbitmq.host | quote }}
  ORCHESTRATOR_RABBITMQ_PORT: {{ .Values.orchestrator.rabbitmq.port | quote }}
  ORCHESTRATOR_RABBITMQ_AUTH_USER: {{ .Values.orchestrator.rabbitmq.auth.username | quote }}
  ORCHESTRATOR_RABBITMQ_AUTH_PASSWORD: {{ .Values.orchestrator.rabbitmq.auth.password | quote }}
  ORCHESTRATOR_RABBITMQ_TLS_ENABLED: {{ $.Values.orchestrator.rabbitmq.tls.enabled | quote }}
  ORCHESTRATOR_RABBITMQ_TLS_CLIENT_CACERT_PATH: "/var/substra/orchestrator_rabbitmq/tls/client/ca.crt"
  ORCHESTRATOR_RABBITMQ_TLS_CLIENT_CERT_PATH: "/var/substra/orchestrator_rabbitmq/tls/client/tls.crt"
  ORCHESTRATOR_RABBITMQ_TLS_CLIENT_KEY_PATH: "/var/substra/orchestrator_rabbitmq/tls/client/tls.key"

  # Organization identity
  LEDGER_MSP_ID: {{ .Values.orchestrator.mspID | quote }}
  # Orchestrator channels configuration
  LEDGER_CHANNELS: {{ .Values.orchestrator.channels | toJson | quote }}
