apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substra.fullname" . }}-events-uwsgi
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}-events
data:
  uwsgi.ini: |
    [uwsgi]
    module                        = backend.wsgi
    http-socket                   = :8000
    ; need-app needs to be set to true, if not, when the app fail, uwsgi will keep running
    need-app                      = true
