apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-wait-init-migrations
  labels:
  {{- include "substra.labels" . | nindent 4 }}
data:
  wait-init-migration.sh: |
    #!/usr/bin/env bash

    # Ensure the django migration have finished running before deploying apps
    for i in {1..10}
    do
        [[ $(./manage.py migrate --check) == 0 ]] && exit
        echo "retrying wait for migration $i"
        sleep 30
    done
    exit 1
