apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-server-uwsgi
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}
data:
  uwsgi.ini: |
    [uwsgi]
    module                        = backend.wsgi
    env                           = DJANGO_SETTINGS_MODULE=backend.settings.server.{{ .Values.settings }}
    static-map                    = /{{ trimAll "/" .Values.server.subpath }}{{ if .Values.server.subpath }}/{{ end }}static=/usr/src/app/backend/statics

    master                        = 1
    processes                     = {{ .Values.server.uwsgiProcesses }}
    threads                       = {{ .Values.server.uwsgiThreads }}

    http-socket                   = :8000

    need-app                      = true
    socket-timeout                = 300
    http-timeout                  = 300
    http-keepalive                = 300
    harakiri                      = 300
    harakiri-verbose              = true
    die-on-term                   = 1
    vacuum                        = true
    buffer-size                   = 65535

    add-header                    = Connection: Keep-Alive
    ignore-sigpipe                = true
    ignore-write-errors           = true
    disable-write-exception       = true
    wsgi-disable-file-wrapper     = true
