apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
data:
  POSTGRESQL_DATABASE: !!str {{ .Values.postgresql.auth.database }}
  POSTGRESQL_HOSTNAME: !!str {{ template "substra-backend.postgresql.host" . }}
  POSTGRESQL_PORT: !!str {{ .Values.postgresql.port }}
