apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-add-account
data:
  users: |
    {{- range .Values.users }}
      {{ .name }} {{ .secret }} {{.channel}}
    {{- end }}
  incoming_nodes: |
    {{- range .Values.incomingNodes }}
      {{ .name }} {{ .secret }}
    {{- end }}
  outgoing_nodes: |
    {{- range .Values.outgoingNodes }}
      {{ .name }} {{ .secret }}
    {{- end }}
