{{ if .Values.registry.local }}
{{ range $index, $item :=  .Values.registry.prepopulate }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "substra.fullname" $ }}-registry-prepopulate-{{ $index }}
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-registry-prepopulate-{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ template "substra.name" $ }}-registry-prepopulate-{{ $index }}
        {{ include "substra.selectorLabels" $ | nindent 8}}
  template:
    metadata:
      labels:
        {{ include "substra.labels" $ | nindent 8 }}
        app.kubernetes.io/name: {{ template "substra.name" $ }}-registry-prepopulate-{{ $index }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      initContainers:
      - name: wait-registry
        image: jwilder/dockerize
        command: ['dockerize', '-wait', 'tcp://{{ $.Release.Name }}-docker-registry:5000']
      - name: kaniko
        image: {{ $.Values.backend.kaniko.image }}
        args: ["--context=/docker-context",
                {{- if .dstImage }}
                "--destination={{ $.Release.Name }}-docker-registry:5000/{{ .dstImage }}",
                {{- else }}
                "--destination={{ $.Release.Name }}-docker-registry:5000/{{ .image }}",
                {{ end }}
                "--insecure",
                "--verbosity=debug"]
        volumeMounts:
          - name: dockerfile
            mountPath: /docker-context
          {{- if .dockerConfigSecretName }}
          - name: docker-config
            mountPath: /kaniko/.docker
          {{- end }}
      containers:
      - image: gcr.io/google-containers/pause:2.0
        name: pause
      volumes:
      - name: dockerfile
        configMap:
          name: {{ template "substra.fullname" $ }}-registry-prepopulate-dockerfile-{{ $index }}
      {{- if .dockerConfigSecretName }}
      - name: docker-config
        secret:
          secretName: {{ .dockerConfigSecretName }}
          items:
          - key: .dockerconfigjson
            path: config.json
      {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "substra.fullname" $ }}-registry-prepopulate-dockerfile-{{ $index }}
data:
    Dockerfile: |
      {{- if .sourceRegistry }}
      FROM {{ .sourceRegistry }}/{{ .image }}
      {{- else }}
      FROM {{ .image }}
      {{ end }}
{{- end }}
{{- end }}
