{{ if .Values.containerRegistry.local }}
{{ range $index, $item :=  .Values.containerRegistry.prepopulate }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "substra.fullname" $ }}-registry-prepopulate-{{ $index }}
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-registry-prepopulate-{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ template "substra.name" $ }}-registry-prepopulate-{{ $index }}
        {{ include "substra.selectorLabels" $ | nindent 8}}
  template:
    metadata:
      labels:
        {{ include "substra.labels" $ | nindent 8 }}
        app.kubernetes.io/name: {{ template "substra.name" $ }}-registry-prepopulate-{{ $index }}
    spec:
      initContainers:
      - name: wait-registry
        image: jwilder/dockerize:0.6.1
        resources:
          {{- toYaml $.Values.registryPrepopulate.waitRegistry | nindent 12 }}
        command: ['dockerize', '-wait', 'tcp://{{ $.Release.Name }}-docker-registry:5000']
      - name: kaniko
        image: {{ include "common.images.name" $.Values.kaniko.image }}
        resources:
          {{- toYaml $.Values.registryPrepopulate.kaniko.resources | nindent 12 }}
        args:
          - "--context=/docker-context"
          {{- if .dstImage }}
          - "--destination={{ $.Release.Name }}-docker-registry:5000/{{ .dstImage }}"
          {{- else }}
          - "--destination={{ $.Release.Name }}-docker-registry:5000/{{ .image }}"
          {{- end }}
          - "--insecure"
          - "--verbosity=debug"
          - "--kaniko-dir=/kaniko-dir"
        volumeMounts:
          - name: kaniko-dir
            mountPath: /kaniko-dir
          - name: dockerfile
            mountPath: /docker-context
          {{- if .dockerConfigSecretName }}
          - name: docker-config
            mountPath: /kaniko/.docker
          {{- end }}
      containers:
      - image: gcr.io/google-containers/pause:3.2
        name: pause
        resources:
          {{- toYaml $.Values.registryPrepopulate.pause.resources | nindent 12 }}
      volumes:
      - name: kaniko-dir
        emptyDir: {}
      - name: dockerfile
        configMap:
          name: {{ template "substra.fullname" $ }}-registry-prepopulate-dockerfile-{{ $index }}
      {{- if .dockerConfigSecretName }}
      - name: docker-config
        secret:
          secretName: {{ .dockerConfigSecretName }}
          items:
          - key: .dockerconfigjson
            path: config.json
      {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "substra.fullname" $ }}-registry-prepopulate-dockerfile-{{ $index }}
data:
    Dockerfile: |
      {{- if .sourceRegistry }}
      FROM {{ .sourceRegistry }}/{{ .image }}
      {{- else }}
      FROM {{ .image }}
      {{ end }}
{{- end }}
{{- end }}
