{{- if .Values.server.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "substra.server.fullname" . }}
  labels:
    {{ include "substra.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.server.ingress.annotations -}}
    {{- include "common.tplvalues.render" (dict "value" .Values.server.ingress.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.server.ingress.hostname }}
    - host: {{ include "common.tplvalues.render" ( dict "value" .Values.server.ingress.hostname "context" $ ) }}
      http:
        paths:
          {{- if .Values.server.ingress.extraPaths }}
          {{- toYaml .Values.server.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.server.ingress.path }}
            pathType: {{ .Values.server.ingress.pathType }}
            backend:
              service:
                name: {{ template "substra.server.fullname" . }}
                port:
                  name: http
    {{- end }}
    {{- range .Values.server.ingress.extraHosts }}
    - host: {{ include "common.tplvalues.render" ( dict "value" .name "context" $ ) }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ template "substra.server.fullname" $ }}
                port:
                  name: http
    {{- end }}
  {{- if .Values.server.ingress.extraTls }}
  tls:
    {{- include "common.tplvalues.render" (dict "value" .Values.server.ingress.extraTls "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
