{{/*
Delete all the PVCs created by the StatefulSet substra-backend-worker.
This is necessary because kubernetes doesn't automatically delete StatefulSet PVCs.
See: https://github.com/kubernetes/kubernetes/issues/55045
*/}}
{{- if .Values.hooks.deleteWorkerPvc.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "substra.fullname" . }}-hook-delete-worker-pvc
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    {{ include "substra.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{ include "substra.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.hooks.serviceAccount }}
      containers:
        - name: kubectl
          image: {{ include "common.images.name" .Values.hooks.deleteWorkerPvc.image }}
          args:
            - delete
            - pvc
            - --namespace=$(SUBSTRA_NAMESPACE)
            - --ignore-not-found=true
            - -l
            - app.kubernetes.io/name={{ template "substra.name" . }}-worker
          env:
            - name: SUBSTRA_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- end }}
