{{- if .Values.hooks.deleteComputePods.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "substra.fullname" . }}-hook-delete-pods
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    {{ include "substra.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{ include "substra.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.hooks.serviceAccount }}
      containers:
        - name: kubectl
          image: {{ include "common.images.name" .Values.hooks.deleteComputePods.image }}
          args:
            - delete
            - pods
            - --namespace=$(SUBSTRA_NAMESPACE)
            - --ignore-not-found=true
            - --wait=true
            - -l
            - substra.ai/pod-type in (compute-task, image-build)
          env:
            - name: SUBSTRA_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- end }}
