{{- if .Values.backend.kaniko.cache.warmer.images }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "substra.fullname" . }}-kaniko-cache-warmer
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" . }}-kaniko-cache-warmer
spec:
  template:
    metadata:
      labels:
        {{ include "substra.labels" . | nindent 8 }}
    spec:
      # Run the cache warmer on the same node as the worker pod, because
      # they both use the "docker-cache" PV.
      # Use "server" pod affinity (and not "worker" pod) because the server
      # is started earlier, so the warmer can also start earlier. The worker
      # is always scheduled on the same node as the server.
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ template "substra.name" . }}-server
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kaniko-cache-warmer
        image: {{ .Values.backend.kaniko.cache.warmer.image }}
        args:
        - "--cache-dir=/cache"
        {{- range .Values.backend.kaniko.cache.warmer.images }}
        - "--image={{ .image }}"
        {{- end }}
        - "--verbosity=debug"
        volumeMounts:
          - name: kaniko-cache
            mountPath: /cache
            readOnly: False
          {{- if .Values.backend.kaniko.dockerConfigSecretName }}
          - name: docker-config
            mountPath: /kaniko/.docker
          {{- end }}
      restartPolicy: Never
      volumes:
        - name: kaniko-cache
          persistentVolumeClaim:
            claimName: {{ include "substra.fullname" $ }}-docker-cache
        {{- if .Values.backend.kaniko.dockerConfigSecretName }}
        - name: docker-config
          secret:
            secretName: {{ .Values.backend.kaniko.dockerConfigSecretName }}
            items:
            - key: .dockerconfigjson
              path: config.json
        {{- end }}
  backoffLimit: 4

{{- end}}
