apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: substra-backend-server-ingress
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role-server-client: 'true'
    ports:
    - port: {{ .Values.server.service.port }}
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "substra.name" . }}-server
      {{ include "substra.labels" . | nindent 6 }}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: substra-backend-server-egress
spec:
  egress:
  - ports:
    - port: {{ .Values.server.service.port }}
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ template "substra.name" . }}-server
          {{ include "substra.selectorLabels" . | nindent 10}}
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: {{ template "substra.name" . }}
      role-server-client: 'true'
  policyTypes:
  - Egress