apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "substra.name". }}-storage-ingress
spec:
  podSelector:
    matchLabels:
      {{ include "substra-backend.objectStore.labels" . | indent 10 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: {{ template "substra.name" . }}
          role-storage-client: 'true'
    ports:
    - protocol: TCP
      port: {{ include "substra-backend.objectStore.port" . }}
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "substra.name". }}-storage-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: {{ template "substra.name" . }}
      role-storage-client: 'true'
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{ include "substra-backend.objectStore.labels" . | indent 10 }}
    ports:
    - protocol: TCP
      port: {{ include "substra-backend.objectStore.port" . }}
