apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "substra.name". }}-redis-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: master
      app.kubernetes.io/name: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: {{ template "substra.name" . }}
          role-redis-client: 'true'
    ports:
    - protocol: TCP
      port: {{ .Values.redis.master.service.ports.redis }}
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "substra.name". }}-redis-egress
spec:
  podSelector:
    matchLabels:
          app.kubernetes.io/part-of: {{ template "substra.name" . }}
          role-redis-client: 'true'
      
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: master
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: {{ .Values.redis.master.service.ports.redis }}
