{{- if .Values.orchestrator.sameCluster }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "substra.name" . }}-orchestrator-client-egress
spec:
  podSelector:
    matchLabels:
      role-orchestrator-client: 'true'
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 192.168.0.0/16
    - ipBlock:
        cidr: 172.16.0.0/20
    ports:
    - protocol: TCP
      port: {{ .Values.orchestrator.port }}
{{- end -}}
