kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "substra.name". }}-deny-all-backend
spec:
  podSelector: {}
  ingress: []
  egress:
    - to:
      # Allow internal DNS reslution
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
