{{- if not .Values.containerRegistry.local }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "substra.name". }}-registry-remote-egress
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        {{- if not .Values.server.allowLocalRequests }}
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/20
        {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.containerRegistry.port }}
  podSelector:
    matchLabels:
      role-registry-client: 'true'
  policyTypes:
  - Egress
{{- end }}
