{{- if not .Values.database.auth.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra-backend.database.secretName" . }}
  labels:
  {{- include "substra.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.database.auth.password | b64enc | quote }}
  DATABASE_USERNAME: {{ .Values.database.auth.username | b64enc | quote }}
{{- end }}
