{{- if not .Values.database.auth.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ .Values.database.auth.password | quote }}"
  DATABASE_USERNAME: "{{ .Values.database.auth.username | quote }}"
{{- end }}
