apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra.fullname" . }}-redis
  labels:
  {{- include "substra.labels" . | nindent 4 }}
type: Opaque
data:
  CELERY_BROKER_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
