{{- if .Values.privateCa.secret.data }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.privateCa.secret.name }}
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}
stringData:
  {{ .Values.privateCa.secret.fileName }}: |
{{ .Values.privateCa.secret.data | indent 4}}
{{- end }}
