apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
type: Opaque
data:
  BACKEND_DB_PWD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
