{{- if not .Values.postgresql.auth.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra.fullname" . }}-database
  labels:
  {{- include "substra.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRESQL_USERNAME: {{ .Values.postgresql.auth.username | quote }}
{{- end }}