apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra.fullname" . }}-server-key
  labels:
  {{- include "substra.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ randAlphaNum 128 | quote }}