{{- if or (not .Values.minio.auth.secretName) .Values.localstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra-backend.objectStore.secretName" . }}
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}
type: Opaque
data:
  OBJECTSTORE_ACCESSKEY: {{ include "substra-backend.objectStore.accessKey" . | b64enc }}
  OBJECTSTORE_SECRETKEY: {{ include "substra-backend.objectStore.secretKey" . | b64enc }}
{{- end }}
