apiVersion: v1
kind: Secret
metadata:
  name: {{ include "substra.fullname" . }}-objectstore
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}
type: Opaque
data:
  OBJECTSTORE_ACCESSKEY: {{ .Values.minio.auth.rootUser | b64enc }}
  OBJECTSTORE_SECRETKEY: {{ .Values.minio.auth.rootPassword | b64enc }}
