apiVersion: v1
kind: Secret
metadata:
  name: {{ include "substra.fullname" . }}-add-account
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}-add-account
data:
  users: {{ include "common.users" .Values.addAccountOperator.users | b64enc | quote }}
  incoming_nodes: {{ include "common.users" .Values.addAccountOperator.incomingNodes | b64enc | quote }}
  outgoing_nodes: {{ include "common.users" .Values.addAccountOperator.outgoingNodes | b64enc | quote }}
