{{- if not .Values.server.persistence.servermedias.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "substra.fullname" $ }}-servermedias
  labels:
  {{ include "substra.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  # if DataSampleStorageInServerMedia, add labels selector to be able
  # to match PersistanceVolume properly
  {{- if .Values.DataSampleStorageInServerMedia }}
  selector:
    matchLabels:
      {{ include "substra.selectorLabels" . | nindent 8}}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.servermedias.size | quote }}
  {{ include "common.storage.class" .Values.server.persistence.servermedias }}
{{- end }}
