kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "substra.fullname" $ }}-servermedias
  labels:
  {{ include "substra.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistence.servermedias.size | quote }}
  {{ include "common.storage.class" .Values.server.persistence.servermedias }}
