# Generated by Django 2.1.2 on 2019-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalauthent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='internalauthent',
            name='username',
        ),
        migrations.AddField(
            model_name='internalauthent',
            name='modulus',
            field=models.CharField(default='foo', max_length=256),
            preserve_default=False,
        ),
    ]
