# Generated by Django 2.1.2 on 2019-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_auto_20190729_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalauthent',
            name='modulus',
            field=models.CharField(max_length=64),
        ),
    ]
