# Generated by Django 2.2.17 on 2021-01-19 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={},
        ),
        migrations.AlterModelManagers(
            name="channel",
            managers=[],
        ),
    ]
