# Generated by Django 4.0.6 on 2022-08-01 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

from users.models.user_channel import UserChannel


def set_user_role_admin(apps, schema_editor):
    users = apps.get_model("users", "UserChannel")
    for user in users.objects.all():
        user.role = UserChannel.Role.ADMIN
        user.save()


def remove_user_role_admin(apps, schema_editor):
    users = apps.get_model("users", "UserChannel")
    for user in users.objects.all():
        user.role = UserChannel.Role.USER
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_auto_20210119_1103"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="name",
            new_name="channel_name",
        ),
        migrations.AddField(
            model_name="channel",
            name="role",
            field=models.CharField(choices=[("ADMIN", "Admin"), ("USER", "User")], default="USER", max_length=64),
        ),
        migrations.RenameModel(
            old_name="Channel",
            new_name="UserChannel",
        ),
        migrations.RunPython(
            code=set_user_role_admin,
            reverse_code=remove_user_role_admin,
        ),
        migrations.AlterField(
            model_name="userchannel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="channel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
