# Generated by Django 4.1.7 on 2023-03-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_setup_role_userchannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOidcInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("openid_subject", models.CharField(max_length=255)),
                ("valid_until", models.DateTimeField()),
                ("refresh_token", models.CharField(blank=True, max_length=10000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
