# Generated by Django 4.0.7 on 2022-10-12 10:01

from django.db import migrations
from django.db import models


def set_default_ui_preferences(apps, schema_editor):
    users = apps.get_model("users", "UserChannel")
    for user in users.objects.all():
        user.ui_preferences = dict
        user.save()


def remove_default_ui_preferences(apps, schema_editor):
    users = apps.get_model("users", "UserChannel")
    for user in users.objects.all():
        user.ui_preferences = None
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_setup_role_userchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchannel",
            name="ui_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            code=set_default_ui_preferences,
            reverse_code=remove_default_ui_preferences,
        ),
    ]
