# Generated by Django 4.0.7 on 2022-09-28 09:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_setup_role_userchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchannel",
            name="ui_preferences",
            field=models.JSONField(null=True),
        ),
    ]
