# Generated by Django 4.1.7 on 2023-05-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_implicitbearertoken_bearertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bearertoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bearer_tokens", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
