# Generated by Django 4.1.7 on 2023-04-20 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_bearertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="bearertoken",
            name="expiry",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="bearertoken",
            name="note",
            field=models.TextField(default="Empty Note"),
        ),
        migrations.AlterField(
            model_name="bearertoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bearer_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
    ]
