# Generated by Django 4.1.7 on 2023-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_bearertoken_expiry_bearertoken_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bearertoken",
            name="expiry",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
