# Generated by Django 4.2.1 on 2023-08-08 09:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0006_alter_bearertoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="implicitbearertoken",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="implicitbearertoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implicit_bearer_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
