# Generated by Django 2.2.17 on 2021-04-07 12:47

import uuid

from django.db import migrations
from django.db import models

import substrapp.models.datamanager
import substrapp.models.function
import substrapp.models.model


def metric_upload_to(instance, filename) -> str:
    return f"metrics/{instance.key}/{filename}"


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algo",
            fields=[
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=500, upload_to=substrapp.models.function.upload_to)),
                ("description", models.FileField(max_length=500, upload_to=substrapp.models.function.upload_to)),
                ("validated", models.BooleanField(default=False)),
                ("checksum", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="DataManager",
            fields=[
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("data_opener", models.FileField(max_length=500, upload_to=substrapp.models.datamanager.upload_to)),
                ("description", models.FileField(max_length=500, upload_to=substrapp.models.datamanager.upload_to)),
                ("validated", models.BooleanField(blank=True, default=False)),
                ("checksum", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="DataSample",
            fields=[
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("validated", models.BooleanField(default=False)),
                ("path", models.FilePathField(blank=True, max_length=500, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("validated", models.BooleanField(default=False)),
                ("file", models.FileField(max_length=500, upload_to=substrapp.models.model.upload_to)),
                ("checksum", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("creation_date", models.DateTimeField(editable=False)),
                ("last_modified", models.DateTimeField(editable=False)),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("validated", models.BooleanField(blank=True, default=False)),
                (
                    "description",
                    models.FileField(blank=True, max_length=500, null=True, upload_to=metric_upload_to),
                ),
                (
                    "address",
                    models.FileField(blank=True, max_length=500, null=True, upload_to=metric_upload_to),
                ),
                ("checksum", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
