# Generated by Django 2.2.24 on 2021-08-16 22:17

from django.conf import settings
from django.db import migrations
from django.db import models

import substrapp.models.datasample
import substrapp.models.model


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasample",
            name="path",
            field=models.FilePathField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datasample",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=settings.DATASAMPLE_STORAGE,
                upload_to=substrapp.models.datasample.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="datasample",
            name="checksum",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="model",
            name="file",
            field=models.FileField(
                max_length=500, storage=settings.MODEL_STORAGE, upload_to=substrapp.models.model.upload_to
            ),
        ),
    ]
