# Generated by Django 2.1.2 on 2019-10-31 09:10

from django.db import migrations, models
import substrapp.models.compositealgo


class Migration(migrations.Migration):

    dependencies = [
        ('substrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeAlgo',
            fields=[
                ('pkhash', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=substrapp.models.compositealgo.upload_to)),
                ('description', models.FileField(max_length=500, upload_to=substrapp.models.compositealgo.upload_to)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
