# Generated by Django 2.2.24 on 2021-12-03 14:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0003_computeplanmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEntrypoint",
            fields=[
                ("asset_key", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("entrypoint_json", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
