# Generated by Django 2.2.24 on 2021-12-13 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0004_imageentrypoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algo",
            name="validated",
        ),
        migrations.RemoveField(
            model_name="datamanager",
            name="validated",
        ),
        migrations.RemoveField(
            model_name="datasample",
            name="validated",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="validated",
        ),
        migrations.RemoveField(
            model_name="model",
            name="validated",
        ),
    ]
