# Generated by Django 4.0.4 on 2022-04-27 12:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0007_alter_algo_description_alter_algo_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageentrypoint",
            name="entrypoint_json",
            field=models.JSONField(),
        ),
    ]
