# Generated by Django 4.0.3 on 2022-05-05 09:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0009_delete_metric"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageentrypoint",
            name="asset_key",
        ),
        migrations.AddField(
            model_name="imageentrypoint",
            name="algo_checksum",
            field=models.CharField(
                default="invalid", editable=False, max_length=256, primary_key=True, serialize=False
            ),
        ),
    ]
