# Generated by Django 4.0.7 on 2022-09-02 13:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0010_remove_imageentrypoint_asset_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerLastEvent",
            fields=[
                ("channel", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("event_id", models.CharField(blank=True, default="", max_length=250, null=True)),
            ],
        ),
    ]
