# Generated by Django 4.0.7 on 2022-10-11 17:31

import django.core.files.storage
from django.db import migrations
from django.db import models

import substrapp.models.asset_failure_report
import substrapp.models.datamanager
import substrapp.models.function


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0012_alter_algo_description_alter_algo_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algo",
            name="description",
            field=models.FileField(
                max_length=500,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.function.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="algo",
            name="file",
            field=models.FileField(
                max_length=500,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.function.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="computetaskfailurereport",
            name="logs",
            field=models.FileField(
                max_length=36,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.asset_failure_report._upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="datamanager",
            name="data_opener",
            field=models.FileField(
                max_length=500,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.datamanager.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="datamanager",
            name="description",
            field=models.FileField(
                max_length=500,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.datamanager.upload_to,
            ),
        ),
    ]
