# Generated by Django 4.0.7 on 2023-02-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("substrapp", "0013_alter_algo_description_alter_algo_file_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Algo",
            new_name="Function",
        ),
        migrations.RenameField(
            model_name="imageentrypoint",
            old_name="algo_checksum",
            new_name="function_checksum",
        ),
    ]
