# Generated by Django 4.1.7 on 2023-08-11 11:30

import django.db.models.deletion
from django.db import migrations
from django.db import models

import substrapp.models.datamanager
import substrapp.models.function
import substrapp.storages.minio


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0015_alter_computetaskfailurereport_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        storage=substrapp.storages.minio.MinioStorage("substra-function"),
                        upload_to=substrapp.models.function.upload_to_function,
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "function",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="substrapp.function"),
                ),
            ],
        ),
    ]
