# Generated by Django 4.2.3 on 2023-09-07 07:31

import django.core.files.storage
from django.db import migrations
from django.db import models

import substrapp.models.compute_task_failure_report
import substrapp.models.function


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0016_add_functionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computetaskfailurereport",
            name="logs",
            field=models.FileField(
                max_length=36,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.compute_task_failure_report._upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="functionimage",
            name="file",
            field=models.FileField(
                max_length=500,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.function.upload_to_function,
            ),
        ),
    ]
