# Generated by Django 4.1.7 on 2024-01-11 15:49

import urllib.parse

import django.core.files.storage
from django.conf import settings
from django.db import migrations
from django.db import models

import api.models.utils
import substrapp.models.asset_failure_report


def compute_default(apps, schema_editor):
    failure_reports = apps.get_model("substrapp", "assetfailurereport")
    for report in failure_reports.objects.all().iterator():
        logs_path = f"lofgs/{report.asset_key}/file/"
        report.logs_address = urllib.parse.urljoin(settings.DEFAULT_DOMAIN, logs_path)
        report.logs_owner = settings.MSP_ID
        report.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0016_rename_computetaskfailurereport_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="assetfailurereport", name="logs_address", field=models.URLField(null=True)),
        migrations.AddField(
            model_name="assetfailurereport", name="logs_owner", field=models.CharField(max_length=100, null=True)
        ),
        migrations.RunPython(compute_default, reverse_func),
        migrations.AlterField(
            model_name="assetfailurereport",
            name="logs_owner",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="assetfailurereport",
            name="logs_address",
            field=models.URLField(validators=[api.models.utils.URLValidatorWithOptionalTLD()]),
        ),
        migrations.AlterField(
            model_name="assetfailurereport",
            name="logs",
            field=models.FileField(
                max_length=36,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.asset_failure_report._upload_to,
            ),
        ),
    ]
