# Generated by Django 4.1.7 on 2023-08-23 10:03

import django.core.files.storage
from django.db import migrations
from django.db import models

import substrapp.models.celery_task_failure_report
import substrapp.models.function


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0016_add_functionimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskFailureReport",
            fields=[
                ("asset_key", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("asset_type", models.CharField(max_length=100)),
                (
                    "logs",
                    models.FileField(
                        max_length=36,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=substrapp.models.celery_task_failure_report._upload_to,
                    ),
                ),
                ("logs_checksum", models.CharField(max_length=64)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ComputeTaskFailureReport",
        ),
        migrations.AlterField(
            model_name="functionimage",
            name="file",
            field=models.FileField(
                max_length=500,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.function.upload_to_function,
            ),
        ),
    ]
