# Generated by Django 4.2.3 on 2023-08-30 15:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0016_add_functionimage"),
    ]

    operations = [
        migrations.RenameModel("ComputeTaskFailureReport", "AssetFailureReport"),
        migrations.RenameField("AssetFailureReport", "compute_task_key", "asset_key"),
        migrations.AddField(
            model_name="assetfailurereport",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("FAILED_ASSET_UNKNOWN", "Failed Asset Unknown"),
                    ("FAILED_ASSET_COMPUTE_TASK", "Failed Asset Compute Task"),
                    ("FAILED_ASSET_FUNCTION", "Failed Asset Function"),
                ],
                default="FAILED_ASSET_UNKNOWN",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
