# Generated by Django 4.2.3 on 2023-09-06 15:58

import django.core.files.storage
from django.db import migrations
from django.db import models

import substrapp.models.asset_failure_report
import substrapp.models.function


class Migration(migrations.Migration):
    dependencies = [
        ("substrapp", "0017_rename_computetaskfailurereport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetfailurereport",
            name="logs",
            field=models.FileField(
                max_length=36,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=substrapp.models.asset_failure_report._upload_to,
            ),
        ),
    ]
