# Generated by Django 4.1.7 on 2023-10-02 10:00

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_function_image_address_function_image_checksum"),
        ("substrapp", "0020_rename_archive_checksum_imageentrypoint_function_checksum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functionimage",
            name="id",
        ),
        migrations.AlterField(
            model_name="functionimage",
            name="function",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="api.function"
            ),
        ),
    ]
