---
name: Build substra-backend-metrics-exporter image
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/metrics-exporter/*'
      - 'metrics-exporter/**'
      - '.github/workflows/gcr-metrics.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
          echo "BACKEND_VERSION=latest+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
          echo "BACKEND_VERSION=`echo $GITHUB_REF | cut -d / -f 3`+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        fi

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: 'ghcr.io/substra/connect-backend-metrics-exporter'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: ${{ github.event_name != 'pull_request' }}
        file: ./docker/metrics-exporter/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        build-args: BACKEND_VERSION=${{ env.BACKEND_VERSION }}
