name: "Conventional PR title"

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional_title:
    uses: substra/substra-gha-workflows/.github/workflows/conventional-pr.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


