name: Docker build
on:
  workflow_dispatch:
    inputs:
      force-publish:
        description: Force publishing the image
        type: boolean
        default: false
        required: false
  push:
    branches: [main]
  release:
    types: [published, edited]
  pull_request:
    branches: [main]

concurrency: 
  group: "${{ github.workflow_ref }} - ${{ github.ref }} - ${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  backend:
    uses: substra/substra-gha-workflows/.github/workflows/docker-build.yaml@main
    with:
      image: substra-backend
      force-publish: ${{ github.event.inputs.force-publish || false }}
  
  ca-cert-injector:
    uses: substra/substra-gha-workflows/.github/workflows/docker-build.yaml@main
    with:
      image: substra-backend-ca-cert-injector
      image-folder: ca-cert-injector
      force-publish: ${{ github.event.inputs.force-publish || false }}

  metrics-exporter:
    uses: substra/substra-gha-workflows/.github/workflows/docker-build.yaml@main
    with:
      image: substra-backend-metrics-exporter
      image-folder: metrics-exporter
      force-publish: ${{ github.event.inputs.force-publish || false }}
