---
name: Build connect backend image
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
    paths:
      - 'docker/connect-backend/*'
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
          echo "BACKEND_VERSION=latest+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
          echo "BACKEND_VERSION=`echo $GITHUB_REF | cut -d / -f 3`+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        fi

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v3
      with:
        images: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/connect-backend'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        file: ./docker/connect-backend/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        build-args: BACKEND_VERSION=${{ env.BACKEND_VERSION }}
