name: Helm

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "charts/**"
  workflow_dispatch:
    inputs:
      publish-alpha:
        description: |
          Publish alpha chart. Chart version must be X.Y.Z-alpha.N.
        type: boolean
        required: false
        default: false

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test-generate-publish:
      uses: substra/substra-gha-workflows/.github/workflows/helm.yml@test-gha-n2
      secrets: inherit
      with:
        helm-repositories: '[{"name": "bitnami", "url": "https://charts.bitnami.com/bitnami"},{"name": "std-helm", "url": "https://charts.helm.sh/stable"},{"name": "twumi", "url": "https://helm.twun.io"},{"name": "localstack", "url": "https://localstack.github.io/helm-charts"}]'
        publish-alpha: ${{ inputs.publish-alpha == true }}
        # blanck
