name: Helm

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "charts/**"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v3.5
        with:
          version: "v3.12.0"
        id: install

      - name: Install tools
        run: |
          sudo snap install yq

      - name: Build dependencies
        run: helm dep update charts/substra-backend

      - name: Lint Chart
        run: helm lint charts/substra-backend

      - name: Validate version increment
        run: |
          helm repo add substra https://substra.github.io/charts

          RES=$(helm search repo substra/substra-backend --version $(yq eval .version charts/substra-backend/Chart.yaml))

          if [ "${RES}" == "No results found" ]; then
            echo "Version incremented"
          else
            echo "Validation failed, you should upgrade the chart version in Chart.yaml"
            exit 1
          fi
      - name: Validate Chart.lock changes
        run: |
          CHART_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep Chart.yaml)
          for chart in $CHART_FILES; do
            DIR=$(dirname $chart)
            helm dependency update $DIR
            git diff --exit-code $DIR/Chart.lock || echo "$DIR/Chart.lock needs to be updated!" >&2
          done


  generate-chart-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v4
        with:
          repository: "bitnami-labs/readme-generator-for-helm"
          ref: "2.5.0"
          path: readme-generator-for-helm

      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - uses: actions/checkout@v4
        with:
          path: backend

      - name: Execute readme-generator-for-helm
        run: readme-generator-for-helm/bin/index.js -r backend/charts/substra-backend/README.md -v backend/charts/substra-backend/values.yaml

      - name: Check diff
        run: |
          cd backend/
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          else
            echo "There should be no change generated, please run 'make doc' in backend/charts/ to update the chart README.md"
            git diff
            exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - test
      - generate-chart-readme
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v3.5
        with:
          version: "v3.12.0"
        id: install

      - name: Add dependencies repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add std-helm https://charts.helm.sh/stable
          helm repo add twuni https://helm.twun.io

      - name: Package chart
        run: |
          helm dep build charts/substra-backend
          helm package charts/substra-backend

      - name: Clone Substra charts
        uses: actions/checkout@v4
        with:
          repository: Substra/charts
          ref: "main"
          token: ${{ secrets.CHARTS_GITHUB_TOKEN }}
          path: substra-charts

      - name: Publish chart
        run: |
          mv substra-backend-$(grep -e "^version" charts/substra-backend/Chart.yaml | cut -c10-).tgz substra-charts/
          cd substra-charts
          helm repo index .
          git add .
          git config --global user.email "gh-actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -s --message "GitHub Action: ${{ github.repository }}@${{ github.sha }}"
          git push --quiet --set-upstream origin main
