name: Helm

on:
  push:
    branches:
      - "master"
    paths:
      - "charts/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "charts/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: "v3.5.0"
        id: install
      - name: Install tools
        run: |
          sudo snap install yq
      - name: Build dependencies
        run: helm dep update charts/substra-backend
      - name: Lint Chart
        run: helm lint charts/substra-backend
      - name: Validate version increment
        env:
          HARBOR_AUTH_TOKEN: ${{ secrets.HARBOR_AUTH_TOKEN }}
          HARBOR_AUTH_USER: "robot$connect-backend+connect-backend-pusher"
        run: |
          helm repo add --username=$HARBOR_AUTH_USER --password=$HARBOR_AUTH_TOKEN owkin-priv https://core.harbor.tooling.owkin.com/chartrepo/connect-backend

          RES=$(helm search repo owkin-priv/substra-backend --version $(yq eval .version charts/substra-backend/Chart.yaml))

          if [ "${RES}" == "No results found" ]; then
            echo "Version incremented"
          else
            echo "Validation failed, you should upgrade the chart version in Chart.yaml"
            exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: "v3.5.0"
        id: install
      - name: Install tools
        run: |
          sudo snap install yq
          helm plugin install https://github.com/chartmuseum/helm-push
      - name: Add dependencies repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add std-helm https://charts.helm.sh/stable
          helm repo add twuni https://helm.twun.io
      - name: Package chart
        env:
          HARBOR_AUTH_TOKEN: ${{ secrets.HARBOR_AUTH_TOKEN }}
          HARBOR_AUTH_USER: "robot$connect-backend+connect-backend-pusher"
        run: |
          helm dep build charts/substra-backend
          helm package charts/substra-backend
          helm repo add --username=$HARBOR_AUTH_USER --password=$HARBOR_AUTH_TOKEN owkin-priv https://core.harbor.tooling.owkin.com/chartrepo/connect-backend
          helm push substra-backend-$(yq eval .version charts/substra-backend/Chart.yaml).tgz owkin-priv
