name: Helm

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "charts/**"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test-generate-publish:
      uses: substra/substra-gha-workflows/.github/workflows/helm.yml@main
      with:
        helm-repositories: '[{"name": "bitnami", "url": "https://charts.bitnami.com/bitnami"},{"name": "std-helm", "url": "https://charts.helm.sh/stable"},{"name": "twumi", "url": "https://helm.twun.io"}]'
