name: Python

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  lint_and_tests:
    name: Lint and tests
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r backend/requirements.txt
      - name: Install tools
        run: pip install flake8==3.9.2 pep8-naming==0.12.0
      - name: Lint
        run: flake8 backend/
      - name: Test
        run: |
          cd backend/
          coverage run manage.py test
