name: Python

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"
    paths:
      - "backend/**"
      - "metrics-exporter/**"
      - "fixtures/**"

jobs:
  lint_and_tests:
    name: Lint and tests
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.test
      SRC_DIRS: backend metrics-exporter fixtures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r backend/dev-requirements.txt
      - name: Check formatting - Black
        run: |
          black --check --diff $SRC_DIRS
      - name: Check formatting - isort
        run: |
          isort --check $SRC_DIRS
      - name: Lint
        run: |
          # TODO: run Flake8 on fixtures as well
          flake8 backend metrics-exporter
      - name: Test
        run: |
          cd backend/
          coverage run manage.py test
