name: Python

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  lint_and_tests:
    name: Lint and tests
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.test
      SRC_DIRS: backend metrics-exporter fixtures
      BACKEND_DB_NAME: substra
      BACKEND_DB_USER: postgres
      BACKEND_DB_PWD: postgres
      BACKEND_DB_HOST: localhost
      BACKEND_DB_PORT: 5432
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: substra
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r backend/dev-requirements.txt
      - name: Check formatting - Black
        run: |
          black --check --diff $SRC_DIRS
      - name: Check formatting - isort
        run: |
          isort --check $SRC_DIRS
      - name: Lint
        run: |
          flake8 $SRC_DIRS
      - name: Test
        run: |
          cd backend/
          coverage run manage.py test
